amundsen-io/amundsendatabuilder

- databuilder/loader/file_system_neo4j_csv_loader.py
- databuilder/utils/closer.py
- setup.py
Tested in TARS.
- Added shutdown hook for Closer
- Added force create folder for neo4j loader
> [DPTOOLS-1858] Add shutdown hook for Closer

- example/scripts/sample_data_loader.py
Fix issue https://github.com/lyft/amundsendatabuilder/issues/7
1. Add a JOB_PUBLISH_TAG to the config.
2. Make example directory python package discoverable.
> Fix sample_data_loader script

- databuilder/models/table_column_usage.py
- databuilder/models/table_owner.py
- databuilder/models/user.py
- setup.py
- tests/unit/models/test_table_column_usage.py
- tests/unit/models/test_table_owner.py
- tests/unit/models/test_user.py
- Create a separate class for User model with the user attributes we need from Amundsen People
- Remove User model from exist table_column_usage model
> Add User node with different user attributes

- databuilder/extractor/neo4j_extractor.py
- databuilder/extractor/neo4j_search_data_extractor.py
- databuilder/extractor/table_column_usage_aggregate_extractor.py
- setup.py
- tests/unit/extractor/test_neo4j_search_data_extractor.py
Added "WHERE" clause on the CYPHER filter to filter the record with "published_tag".
Unit & Integration tested
> [DPTOOLS-1903] Remove stale data in ES index

- databuilder/models/user.py
- setup.py
- tests/unit/models/test_table_column_usage.py
> Update user model

- databuilder/models/user_elasticsearch_document.py
- databuilder/transformer/elasticsearch_document_transformer.py
- setup.py
- tests/unit/models/test_table_elasticsearch_document.py
- tests/unit/models/test_user_elasticsearch_document.py
1. Create a userESDoc for user ES document
2. modify ES_transformer to handle different ES Doc type
3. test
> Modify es transformer to support new ES document

- requirements.txt
Upgrade sqlalchemy version to fix https://nvd.nist.gov/vuln/detail/CVE-2019-7164
> Update requirements to fix CVE

- example/scripts/sample_data_loader.py
Add job to the sample data loader which fill(publish) search data into Elasticsearch.
> Add Elasticseach sample publisher

- requirements.txt
- setup.py
Upgrade Neo4j bolt driver to 1.7.2
> [DPTOOLS-2210] Upgrade Neo4j bolt driver to the latest

- .travis.yml
based on @ttannis https://github.com/lyft/amundsenfrontendlibrary/pull/138/files
> Add codecov for databuilder repo

- README.md
- databuilder/callback/call_back.py
- databuilder/job/job.py
- databuilder/publisher/base_publisher.py
- databuilder/publisher/elasticsearch_publisher.py
- databuilder/publisher/neo4j_csv_publisher.py
- setup.py
- tests/unit/callback/test_call_back.py
- tests/unit/publisher/test_publisher.py
Introduce Callback into Databuilder.
From "README.MD":
Callback interface is built upon a Observer pattern where the participant want to take any action when target's state changes.
Publisher is the first one adopting Callback where registered Callback will be called either when publish succeeded or when publish failed. In order to register callback, Publisher provides register_call_back method.
One use case for Extractor needs to commit when job is finished. Having Extractor register a callback to Publisher to commit when publish is successful, extractor can safely commit by implementing commit logic into on_success method.
Added unit tests. Performed integration tests.
Added documentation 
https://github.com/lyft/amundsendatabuilder/tree/jinchang-callback-registration#callback
Make sure …
> [DPTOOLS-2312] Add callback registration in Publisher

- databuilder/publisher/elasticsearch_publisher.py
> No need to show the exceptions body info when index not found

- example/scripts/sample_data_loader.py
Discussion found in https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1558721194000600?thread_ts=1558633608.153700&cid=CHQERT0D7
> Change the ES address to localhost

- .travis.yml
Skip existing version on Pypi
N/A. Config change on Travis CI.
N/A
> Skip existing version on Pypi

- databuilder/extractor/bigquery_metadata_extractor.py
- tests/unit/extractor/test_bigquery_metadata_extractor.py
Bigquery can contain data partitioned by date where each day goes into a separate table. These are not day-partitioned tables (which uses a column to separate the data), but an old style of bigquery. A good example is "ga_sessions_", which are dumped automatically from google analytics data (see: https://support.google.com/analytics/answer/4419694?hl=en). Because each day is essentially a new table, amundsen will retrieve metadata for each and every day. To avoid this, I added this code as a proposal to deal with this method of date partitioned tables. The reason why Google uses this method for Google Analytics is because the schema can then be modified in the future.
I added a test to verify only one table definition is returned, even if two tables exist for the date range.
> Avoids duplicate metadata for table date ranges

- databuilder/extractor/kafka_source_extractor.py
- databuilder/models/table_metadata.py
- setup.py
- tests/unit/extractor/test_kafka_source_extractor.py
- tests/unit/models/test_table_metadata.py
Build a relation between table and tag as well as col and tag.
> Support table/col tag in table metadata model

- databuilder/transformer/elasticsearch_document_transformer.py
- setup.py
- tests/unit/transformer/test_elasticsearch_document_transfer.py
Generalize how ESDocument model is imported and used in ElasticsearchDocumentTransformer
_What tests did you add or modify and why? 
1. Added test to ensure that if no model_class conf is provided for ElasticsearchDocumentTransformer, Exception() will be thrown.
2. Added test to ensure if model_class conf is provided for ElasticsearchDocumentTransformer is invalid, Exception() will be thrown.
- All the public functions and the classes in the PR contain …
> generalize ElasticsearchDocumentTransformer

- setup.py
> Increase version for Preprocessor

- databuilder/publisher/neo4j_csv_publisher.py
- setup.py
Add updated timestamp into node and relation. This will enable certain feature such as pagination.
Performed integration test.
> [AMD-149] Add updated timestamp into node and relation

- example/scripts/sample_data_loader.py
* Add neo4j_es_last_updated to `sample_data_loader.py` - this moves us one tiny step closer to the Quickstart being picture-perfect compared to those shiny screenshots.
* Fix a few small comment nits 
None - just following suit with state of the current sample loader
Nothing - but sample code with what is still an improvement over status quo - A consequence of adding this is we now get updated indexing info for each sample loader run in the footer:
> Add neo4j_es_last_updated to `sample_data_loader.py`

- databuilder/extractor/bigquery_usage_extractor.py
- setup.py
1. Add exception handling when certain record missing required fields.
2. Add sleep/delay when hitting BQ quota limit.
> Add delay handling in BQ usage extractor

- example/dags/postgres_sample_dag.py
> Update postgres sample dag

- databuilder/extractor/neo4j_search_data_extractor.py
- databuilder/models/table_elasticsearch_document.py
- setup.py
- tests/unit/extractor/test_neo4j_extractor.py
- tests/unit/loader/test_file_system_elasticsearch_json_loader.py
- tests/unit/models/test_table_elasticsearch_document.py
Modify TableESDocument to match its field name to the one used in search service(https://github.com/lyft/amundsensearchlibrary/blob/master/search_service/models/table.py).
Currently we do some field name transformation in search which is not ideal once we have different search document. 
- All the public functions and the classes in the PR contain …
> Refactor tableESDocument to match schema in search service

- databuilder/publisher/elasticsearch_publisher.py
- setup.py
We change the name of the field. So we need to update the index mapping as well.
> Update table ES document

- databuilder/models/user.py
- setup.py
- tests/unit/models/test_user.py
Extend user model to accept any K/V attributes which is same as our table metadata model. 
Unit test
> Extend user model to accept any KV attribute

- example/models/test_column_usage_model.py
- example/sample_data/sample_column_usage.csv
- example/scripts/sample_data_loader.py
* added example for usage data
* this is example data, so, no tests, though, I did test this on an ec2 instance and it worked as expected
* self documenting
> Fix for ISSUE 98 - add example for usage data

- databuilder/extractor/athena_metadata_extractor.py
- example/dags/athena_sample_dag.py
- requirements.txt
- tests/unit/extractor/test_athena_metadata_extractor.py
Added Athena sample dag that uses Athena metadata extractor
Added Unit test for Athena metadata extractor
Added Extractor for Athena metadata
Added sample dag for Athena metadata extractor
Added requirement `PyAthena[SQLAlchemy]` 
Added Unit test for Athena metadata extractor
- [V ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [V ] PR includes a summary of changes. 
- [V ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ …
> Added Extractor for Athena metadata

- databuilder/models/table_source.py
- tests/unit/models/test_table_source.py
Add table source model for users to link github source file with table.
> Add table source model

- setup.py
> Increment the version

- databuilder/publisher/elasticsearch_publisher.py
- setup.py
Allow to index db field and do advanced search.
> Allow search all tables under same db

- README.md
- databuilder/extractor/snowflake_metadata_extractor.py
- example/scripts/sample_snowflake_data_loader.py
- requirements.txt
- setup.py
- tests/unit/extractor/test_snowflake_metadata_extractor.py
Add Snowflake extractor, strongly inspired by PostgresMetadataExtractor. Thanks!
Same tests as for PostgresMetadataExtractor, add DATABASE_KEY check.
Add documentation and sample load script
> Add Snowflake Extractor

- databuilder/extractor/postgres_metadata_extractor.py
See #108 
Using Six, include logic for encoding the database key string if using Python2.7
Need guidance for writing py2/py3 compatibility tests
Addresses the same issue as #108 
> Support Python3 for PostgresMetadataExtractor

- example/models/test_column_model.py
Fixed bad reference to `DESCRIPTION_NODE_LABEL` as it is not a class member.
No tests added or modified as this was a runtime code error.
No changes.
> Fixed bad reference to DESCRIPTION_NODE_LABEL

- setup.py
Internally Lyft uses requirement.txt file to install package. Hence we don't catch the issues listed at https://github.com/lyft/amundsensearchlibrary/pull/46/files. But this pr does the same for databuilder repo. 
> Fix setup script for databuilder repo

- example/models/test_column_usage_model.py
Minor fix.
I tried to print TestColumnUsageModel  - and it wasn't too happy.
None
> Fix testcolumnusagemodel __repr__

- MANIFEST.in
- setup.py
Previously the requirements.txt file is not included in pypi source distribution. Fix the source distribution.
> Fix source distribution

- databuilder/models/user.py
> Remove print line in model

- .github/PULL_REQUEST_TEMPLATE.md
Removed `SQUASH COMMIT` from the PR template
> Removed `SQUASH COMMIT` from the PR template

- requirements.txt
- setup.py
> Relax dependency to make it range

- README.md
Will scroll past GitHub repo folders (specially more handy on small screens like phones/tablets)
> Link deeper to doc content

- setup.py
> Bump the version

- example/sample_data/sample_source.csv
- example/scripts/sample_data_loader.py
Added sample project source data and loader to sample data loader.
No tests added based on what has been happening for sample data loader.
No documentation added.
> Adding sample source data and loader (lyft/amundsen#130)

- example/sample_data/sample_table_last_updated.csv
- example/scripts/sample_data_loader.py
Adding table last update to sample data loader.
No tests added.
No documentation added.
> adding table last updated sample data. (lyft/amundsen#63)

- databuilder/extractor/bigquery_usage_extractor.py
> Add credential handling to BQ usage

- databuilder/job/job.py
PyCharm's highlights were very confusing.
Two types were just reversed.
No tests modified.
No documentation updated.
> Correct type annotation for DefaultJob init

- README.md
- databuilder/extractor/cassandra_extractor.py
- requirements.txt
- tests/unit/extractor/test_cassandra_extractor.py
Add an apache cassandra extractor
Add tests to run extractor mocking responses and filter function
Add docs on how to use the extractor
> add cassandra extractors, tests and docs

- databuilder/extractor/base_bigquery_extractor.py
- databuilder/extractor/bigquery_metadata_extractor.py
- databuilder/extractor/bigquery_usage_extractor.py
- databuilder/extractor/bigquery_watermark_extractor.py
- tests/unit/extractor/test_bigquery_metadata_extractor.py
- tests/unit/extractor/test_bigquery_usage_extractor.py
- tests/unit/extractor/test_bigquery_watermark_extractor.py
Initial working implementation of a BigQuery watermark extractor. As discussed in Slack, there is a fair bit of code duplication with the other BigQuery extractors, so there will be some refactoring still to do. I've also implemented handling for tables sharded by date suffix (e.g. `my_table_20190101`), the tests are good but we don't use sharded tables so I haven't tested it on a real dataset.
New unit test covering the logic in the new extractor.
- All the …
> Implement BigQuery Watermark Extractor for extracting partition ranges

- setup.py
> bump pypi version

- .travis.yml
- requirements.txt
- setup.py
Put some deps into extra_require
Follow https://setuptools.readthedocs.io/en/latest/setuptools.html
> Update the dep and move connector to extra_require

- databuilder/extractor/bigquery_metadata_extractor.py
- tests/unit/extractor/test_bigquery_metadata_extractor.py
Adds a check to allow us to pull tables without schemas
Added a NO_SCHEMA test. Almost like the NO_COL test, but with the schema completely missing. 
No Documentation Changed
> Adding a check to allow us to pull tables without schemas

- README.md
- databuilder/extractor/dashboard/mode_dashboard_extractor.py
- databuilder/extractor/restapi/rest_api_extractor.py
- databuilder/models/dashboard_metadata.py
- databuilder/rest_api/base_rest_api_query.py
- databuilder/rest_api/rest_api_query.py
- requirements.txt
- setup.py
- tests/unit/extractor/restapi/test_rest_api_extractor.py
- tests/unit/models/test_dashboard_metadata.py
- tests/unit/rest_api/test_rest_api_query.py
- Introducing ModeDashboardExtractor that extracts `dashboard group name`, `dashboard group description`, `dashboard name`, `dashboard description`
- Introducing RestAPIQuery that supports `JOIN` operation and extensible for other authentication scheme and different kind of pagination.
From docstring of RestAPIQuery:
A generic `RestApiQuery` that can be joined with other RestApiQuery.
Major feature of RestApiQuery is the fact that it is joinable with other RestApiQuery.
The main problem that RestAPIQuery is to solve is to have a REST API query abstraction that works with most of REST API model with extension point, and make it joinable with multiple REST API queries.
Two main challenges arises in RestAPIQuery:
1. How to retrieve values that I want from the REST API's result. (value …
> Mode Dashboard extractor with Generic REST API Query

- databuilder/extractor/hive_table_last_updated_extractor.py
- setup.py
Addressed problem from `hive_table_last_updated_extractor`
Integration test
N/A
> Follow up patches on v2 field name changes

- databuilder/extractor/dashboard/mode_analytics/mode_dashboard_last_successful_executions_extractor.py
- databuilder/models/dashboard/dashboard_execution.py
- setup.py
Getting last successful execution from Mode's report API. (Mostly reusing the code from `ModeDashboardExecutionsExtractor`)
Incremented minor version as most Dashboard metadata extraction is now ready.
Integration tests and existing unit test.
docstring
> Mode Dashboard last successful execution

- databuilder/extractor/neo4j_search_data_extractor.py
- setup.py
Current Neo4j Cypher query takes quite long time to fetch the record mainly it's joining a lot of nodes that makes it huge number of records and then aggregate.
Optimized version would be performing aggregation as early as possible to reduce it from expanding interim record as well as possible.
Integration test has been done.
N/A
> Optimize Neo4j Cypher query on Neo4jSearchDataExtractor

- requirements.txt
> Remove antlr4 deps

- databuilder/models/dashboard_elasticsearch_document.py
- setup.py
- tests/unit/models/test_dashboard_elasticsearch_document.py
Update the ES document to fit for the design, currently we don't have metric, query in the doc, but we could have it once we have a way to get that metadata for dashboard.
> Update dashboard ES doc

- databuilder/extractor/neo4j_search_data_extractor.py
- tests/unit/extractor/test_neo4j_search_data_extractor.py
The tag now needs to match other entity instead of hard code to table...
> Update the query publish tag to match entity

- README.md
- docs/models.md
Documentation of models
None
WIP
> issue-320 documentation of models

- README.md
Adding BigQuery to the readme. 
> Adding BigQuery to the readme

- databuilder/extractor/dashboard/mode_analytics/mode_dashboard_charts_extractor.py
- databuilder/extractor/dashboard/mode_analytics/mode_dashboard_queries_extractor.py
- databuilder/models/dashboard/dashboard_chart.py
- databuilder/models/dashboard/dashboard_query.py
- setup.py
- tests/unit/models/dashboard/test_dashboard_chart.py
- tests/unit/models/dashboard/test_dashboard_query.py
Added:
- Query model
- Chart model
- ModeDashboardChartsExtractor that extracts chart_id and chart_url. Other metadata is on hold for Mode API response schema is not clear and we are in talk with Mode.
- ModeDashboardQueriesExtractor that extracts query_id, query_name, and query_url
Unit test has been added. Integration test has been done.
docstring
> Add query and chart on Dashboard

- databuilder/models/user.py
- setup.py
- tests/unit/models/test_table_column_usage.py
- tests/unit/models/test_user.py
Add a title field in the user model.
> Add title field in user model

- README.md
- setup.py
> Update python version for databuilder

- databuilder/extractor/db_api_extractor.py
- databuilder/models/column_usage_model.py
- databuilder/models/dashboard/dashboard_usage.py
- databuilder/models/usage/usage_constants.py
- setup.py
- tests/unit/models/dashboard/test_dashboard_usage.py
Added Dashboard usage model.
Added unit test. Performed integration test.
docstring
> Dashboard usage model

- databuilder/publisher/elasticsearch_publisher.py
> Clarify ES publisher warning on first run

- setup.py
> Make the repo py27 and py3 compatible

- example/sample_data/sample_user.csv
- example/scripts/sample_data_loader.py
Add a new attr for user ES model. Modify the sample loader for that.
> Fix sample loader for user ES model

- databuilder/extractor/neo4j_search_data_extractor.py
- databuilder/models/dashboard_elasticsearch_document.py
- setup.py
- tests/unit/models/test_dashboard_elasticsearch_document.py
Update the dashboard ES document based on updated requirement.
> Update dashboard ES document

- databuilder/models/dashboard_elasticsearch_document.py
- setup.py
- tests/unit/models/test_dashboard_elasticsearch_document.py
> Change dashboard ES doc based on latest requirement

- databuilder/extractor/neo4j_search_data_extractor.py
- setup.py
We change the model, we need to change the query as well
> Change default ES dashboard search query

- docs/models.md
Fix the headings in `docs/model.md` so they render correctly on Github.
No tests required for .md files
Fixed headings in `docs/model.md` can be viewed [on my fork|https://github.com/craigrosie/amundsendatabuilder/blob/fix-models-doc-headings/docs/models.md]
> Fix docs/models.md headings

- README.md
- databuilder/extractor/db2_metadata_extractor.py
- example/scripts/sample_db2_data_loader.py
- requirements.txt
- setup.py
A new metadata extractor for Windows, Linux or UNIX Db2 and BigSQL, heavily inspired on the PostgreSQL metadata extractor.
No tests were added or modified, as no internals have changed. I tested the metadata extractor on Db2 on Linux and BigSQL.
I updated the [README.md](README.md) and provided a [sample script](example/scripts/sample_db2_data_loader.py) using the extractor.
I added two dependencies with Apache 2.0 Licenses: 
- [ibm-db-sa-py3](https://pypi.org/project/ibm-db-sa-py3/)
- [ibm-db](https://pypi.org/project/ibm-db/)
- All the public functions …
> Db2 Metadata extractor

- databuilder/extractor/hive_table_metadata_extractor.py
- setup.py
- tests/unit/extractor/test_hive_table_metadata_extractor.py
> Support indexing hive view

- databuilder/extractor/neo4j_search_data_extractor.py
- databuilder/models/table_elasticsearch_document.py
- example/sample_data/sample_schema_description.csv
- example/scripts/sample_data_loader.py
- setup.py
- tests/unit/extractor/test_neo4j_extractor.py
- tests/unit/loader/test_file_system_elasticsearch_json_loader.py
- tests/unit/models/test_table_elasticsearch_document.py
Added Description on Schema for ES document on table
Updated unit test. Integration test done.
N/A
> Added Description on Schema for ES document on table

- example/scripts/sample_postgres_loader.py
Add a sample postgres loader script which requires user to change the connection string.
> Add sample postgres loader script

- README.md
- databuilder/extractor/mysql_metadata_extractor.py
Create a MYSQL metadata extractor.
no need as it covers by existing unit tests.
> Add MYSQL metadata extractor

- README.md
- databuilder/extractor/mssql_metadata_extractor.py
- tests/unit/extractor/test_mssql_metadata_extractor.py
Introducing MS SQL MataData Extractor
1. Empty Query Result
2. Single Query Result
3. Multiple Query Result
4. Schema Filter Clause
5. Cluster Name Tests 
Code is documented at the moment, I'll come with the example in due time.
> MS SQL MataData Extractor

- setup.py
> New release for databuilder

- databuilder/publisher/elasticsearch_publisher.py
- setup.py
Currently we do a bulk update for all the documents at once which we could easily hit by ` it hits 100MB max size limit for the document.`
Test on local staging env.
> Provide configuration to control steps for ES publisher

- README.md
- databuilder/extractor/druid_metadata_extractor.py
- setup.py
Extractor to extract table metadata for an Apache Druid datasource using sqlalchemy connection.
Fix https://github.com/lyft/amundsen/issues/101
Use https://github.com/druid-io/pydruid
Covers by existing sqlalchemy test. 
yes
>  Druid metadata extractor

- databuilder/publisher/neo4j_csv_publisher.py
- setup.py
> Fix encoding issue for publisher

- databuilder/publisher/elasticsearch_constants.py
- databuilder/publisher/elasticsearch_publisher.py
- setup.py
Added Dashboard Elasticsearch mapping
Integration test done
N/A
> Added Dashboard Elasticsearch mapping

- example/sample_data/sample_application.csv
> Update sample loader for application

- example/scripts/sample_data_loader.py
Modify the `sample_data_loader.py`:
* Added a more thorough introductory comment explaining what each of the functions is doing.
* Un-formatted all of the keys, for improved readability for those new to amundsen.
Only doing this for `sample_data_loader.py` for now, since seems to be the typical entrypoint into amundsen. If there's consensus on the lyft end that the best pattern is to have formatted keys, perhaps it makes sense to leave these other scripts as-is. :) 
This is a first step in addressing this: https://github.com/lyft/amundsen/issues/371
None, as this just changes the example code.
Modified the docstring at the top of the sample script.
- In case you are adding a dependency, check if the license complies …
> chore: un-template all of the ConfigFactory keys.

- example/scripts/sample_snowflake_data_loader.py
Updates the `sample_snowflake_data_loader.py` script to match the PG example
No tests were added or modified, this is just the example script.
No documentation was added or modified
> Updates the `sample_snowflake_data_loader.py` script to match the PG example

- databuilder/publisher/elasticsearch_constants.py
- setup.py
https://github.com/lyft/amundsen/issues/433
> Update table search index mapping

- databuilder/publisher/elasticsearch_constants.py
- setup.py
> Fix ES mapping typo

- .github/prlint.json
- setup.py
> chore: add prlint

- databuilder/extractor/dashboard/mode_analytics/mode_dashboard_queries_extractor.py
- databuilder/models/dashboard/dashboard_query.py
- databuilder/transformer/regex_str_replace_transformer.py
- setup.py
- tests/unit/models/dashboard/test_dashboard_query.py
- tests/unit/transformer/test_regex_str_replace_transformer.py
Added SQL query text to Dashboard Query model.
Updated `ModeDashboardQueriesExtractor` to escape backslash on query text for it causes failure on Neo4j.
Integration test done.
N/A
> feat: Add Query text to Dashboard Query model

- requirements.txt
bump the lib to fix security alert
> chore: bump lib deps to fix security alert

- example/sample_data/sample_col.csv
This was preventing the file from being pretty printed in table form by Github.
Removes unintended (?) column in one row of sample data file.
No tests added or modified because this is sample data.
None.
> chore: Removes extra column from sample_col.csv

- .travis.yml
- README.md
- setup.py
> ci: remove py2 ci

- databuilder/extractor/neo4j_search_data_extractor.py
- databuilder/models/dashboard_elasticsearch_document.py
- databuilder/publisher/elasticsearch_constants.py
- setup.py
- tests/unit/models/test_dashboard_elasticsearch_document.py
- Added tags and badges into Dashboard Elasticsearch index
- Optimized Cypher query to perform early aggregation.
- Update Dashboard ES index mapping to make name.raw and group_name.raw to be `case insensitive`.
Integration test done.
N/A
> feat: Added tags and badges into Dashboard Elasticsearch index

- README.md
- databuilder/transformer/generic_transformer.py
- example/sample_data/sample_dashboard_base.csv
- example/sample_data/sample_dashboard_last_execution.csv
- example/sample_data/sample_dashboard_last_modified.csv
- example/sample_data/sample_dashboard_owner.csv
- example/sample_data/sample_dashboard_query.csv
- example/sample_data/sample_dashboard_table.csv
- example/sample_data/sample_dashboard_usage.csv
- example/scripts/sample_data_loader.py
Add Dashboard sample data
Tried out `python3 example/scripts/sample_data_loader.py`
docstring
> other: Add Dashboard sample data

- README.md
- databuilder/extractor/dashboard/redash/redash_dashboard_extractor.py
- databuilder/extractor/dashboard/redash/redash_dashboard_utils.py
- databuilder/rest_api/base_rest_api_query.py
- tests/unit/extractor/dashboard/redash/test_redash_dashboard_extractor.py
- tests/unit/extractor/dashboard/redash/test_redash_dashboard_utils.py
- tests/unit/rest_api/test_rest_api_query.py
Gets dashboard metadata from [Redash](https://redash.io). Quoting from the README:
The included `RedashDashboardExtractor` provides support for extracting basic metadata for Redash dashboards (dashboard name, owner, URL, created/updated timestamps, and a generated description) and their associated queries (query name, URL, and raw query). It can be extended with a configurable table parser function to also support extraction of `DashboardTable` metadata.
Note: `DashboardUsage` and `DashboardExecution` metadata are not supported in this extractor, as these concepts are not supported by the Redash API.
Added unit tests to cover the new code.
Added a section about `RedashDashboardExtractor` to `README.md`.
- In case …
> feat: Add RedashDashboardExtractor for extracting dashboards from redash.io

- databuilder/extractor/glue_extractor.py
- tests/unit/extractor/test_glue_extractor.py
Enhance glue extractor.
1. Fixed missing partition keys
2. Added `is_view`
3. Updated table description
Modified `TestGlueExtractor`
No new functionality added.
> feat: enhance glue extractor

- setup.py
Update to do a minor release for latest databuilder
> chore: update deps for databuilder

- README.md
Signed-off-by: Alagappan Sethuraman <alagappan.als@gmail.com>
Configs for Snowflake metadata extractor was referring postgres metadata extractor. fixed them to have snowflake ones
> docs: Update SnowflakeMetadataExtractor instructions in readme

- databuilder/extractor/snowflake_table_last_updated_extractor.py
https://docs.snowflake.com/en/sql-reference/functions/date_part.html
> fix: correct typo in Snowflake Last Updated extract query

- setup.py
> chore: update version for next release

- example/scripts/sample_postgres_loader.py
> chore: delete csv folder for sample postgres loader

- example/scripts/sample_glue_loader.py
Add a sample script to load AWS Glue data to Neo4j and to Elasticsearch by following https://github.com/amundsen-io/amundsen/issues/542. Make sure your AWS user has access to perform `glue:SearchTables`. If you are assuming specific role, try editing [glue_extractor.py](https://github.com/amundsen-io/amundsendatabuilder/blob/master/databuilder/extractor/glue_extractor.py#L26) to the following.
```
self._glue = boto3.Session(profile_name='YOUR_PROFILE_NAME').client('glue')
```
No tests for the sample scripts.
No documentation added
- All the public …
> feat: add sample_glue_loader script

- setup.py
Bumped version to be 3.3.0
N/A
N/A
> chore: Update setup.py version

- databuilder/publisher/elasticsearch_constants.py
Added multi-fields to `cluster` field on table index mapping
Rerun and verify elasticsearch index mapping changed
issue: https://github.com/amundsen-io/amundsen/issues/712
> fix: Update elasticsearch table index mapping

- README.md
Signed-off-by: Josh Howard <josh.t.howard@ey.com>
Modified README.md by adding
- Dremio extractor code snippet
- Dremio extractor summary
- Link to Dremio homepage
- Link to Dremio driver install instructions
N/A
See summary.
> docs: Added Dremio extractor documentation to README.md

- example/sample_data/sample_tags.csv
Updated sample tags in example data to be default instead go badge since tag like badges no longer supported.
N/A
N/A
> fix: Updated sample tags to be default tags

- setup.py
Forgot to bump up amundsendatabuilder version
N/A
N/A
> chore: Bump version

- README.md
remove two unused badges (we no longer rely on travis)
> chore: remove unused badges

- example/sample_data/sample_watermark.csv
Signed-off-by: Allison Suarez Miranda <asuarezmiranda@lyft.com>
Updated sample_watermark.csv to have all lowercase part_type and fix error from https://github.com/amundsen-io/amundsen/issues/784 .
N/A
N/A
> fix: watermark sample data to lowercase

- databuilder/models/dashboard/dashboard_usage.py
> fix: cast dashboard usage to be int

- example/scripts/sample_data_loader.py
we don't need sqlite any more as we directly ingest from csv file for the quick start demo script.
Rerun the quick start script locally.
> chore: update sample data loader to remove sqlite

- databuilder/extractor/delta_lake_metadata_extractor.py
- example/scripts/sample_deltalake_metadata.py
- setup.py
we should just call delta tables to be `delta` for succinct purposes.
> chore: rename delta-lake to delta

- README.md
Typo in Readme for RedashVisualizationWidget.
> fix: Typo in Readme for RedashVisualizationWidget.

- example/scripts/sample_feast_loader.py
Feast sample job modified to not only do a Feast -> Neo4j extraction, but also Neo4j -> ES publishing. It's better suited for the demo purposes now.
No tests, only sample job modification. Sample job tested manually:
```
root@feast-loader:/# python sample_feast_loader.py feast-feast-core:6565 bolt://neo4j http://amundsen-elasticsearch-client:9200
WARNING:elasticsearch:GET http://amundsen-elasticsearch-client:9200/table_search_index/_alias [status:404 request:0.031s]
WARNING:databuilder.publisher.elasticsearch_publisher:Received index not found error from Elasticsearch. The index doesn't exist for a newly created ES. It's OK on first run.
root@feast-loader:/# 
```
Header in the sample script with usage.
- In case you …
> feat: Sample Feast job with ES publisher

- .github/workflows/monthly_release.yml
- .github/workflows/publish_release.yml
- setup.cfg
Signed-off-by: Allison Suarez Miranda <asuarezmiranda@lyft.com>
Use python-semantic-release to bump version, create new release PRs and publish releases.
> chore: Automate releases

- databuilder/extractor/atlas_search_data_extractor.py
Signed-off-by: mgorsk1 <gorskimariusz13@gmail.com>
Rely on admin metrics instead of basic search for count.
n/a
n/a
> feat: More precise count in Atlas search data extractor

- setup.py
Signed-off-by: Andrew Ciambrone <andrjc4@vt.edu>
Adds boto3 to the neptune requirements. Removing the dependency on the glue dependencies. 
No were needed just a dependency copy over. 
> fix: Add boto3 to neptune dependencies

- databuilder/models/application.py
- databuilder/models/badge.py
- databuilder/models/column_usage_model.py
- databuilder/models/es_last_updated.py
- databuilder/models/table_column_usage.py
- databuilder/models/table_last_updated.py
- databuilder/models/table_lineage.py
- databuilder/models/table_metadata.py
- databuilder/models/table_owner.py
- databuilder/models/table_source.py
- databuilder/models/table_stats.py
- databuilder/models/user.py
- databuilder/models/watermark.py
- tests/unit/models/test_application.py
- tests/unit/models/test_badge.py
- tests/unit/models/test_es_last_updated.py
- tests/unit/models/test_table_last_updated.py
- tests/unit/models/test_table_lineage.py
- tests/unit/models/test_table_owner.py
- tests/unit/models/test_table_source.py
- tests/unit/models/test_table_stats.py
- tests/unit/models/test_user.py
- tests/unit/models/test_watermark.py
Reopened for PR https://github.com/amundsen-io/amundsendatabuilder/pull/448
> refactor: Use yield instead of return for all node/relation iterators in databuilder models

- databuilder/publisher/neptune_csv_publisher.py
Signed-off-by: Andrew Ciambrone <andrjc4@vt.edu>
This was incorrectly using get_config instead of get_string. 
> fix: Correct config getter

- databuilder/serializers/neptune_serializer.py
- requirements.txt
Closes https://github.com/amundsen-io/amundsen/issues/560
This is the last python2 vestige in this repo.
> chore: remove six

- README.md
Closes https://github.com/amundsen-io/amundsen/issues/59
Whitespace and unused variable fixes for a few examples
> docs: minor fixes to README

- databuilder/extractor/atlas_search_data_extractor.py
Signed-off-by: DOMINIK CHOMA <dominik.choma@gmail.com>
Add support for table tags based on Apache Atlas glossary terms
- [ x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [ x] PR includes a summary of changes.
- [x ] PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
- [x ] In case of new functionality, my PR adds documentation that describes how to use it.
- All the public functions and the classes in the PR contain docstrings …
> feat: add support for tags based on atlas terms

- databuilder/extractor/csv_extractor.py
- example/sample_data/sample_badges.csv
- example/sample_data/sample_col.csv
- tests/unit/extractor/test_csv_extractor.py
Signed-off-by: Grant Seward <grant@stemma.ai>
The changes made allow multiple badges to be created within a single record on from the CSV extractors (`CsvTableBadgeExtractor` & `CsvTableColumnExtractor`) and addresses the issue: https://github.com/amundsen-io/amundsen/issues/900
Currently users would need to create one record for each badge, an example may look like:
```text
name,category,database,cluster,schema,table_name
beta,table_status,hive,gold,test_schema,test_table1
tag2,table_status,hive,gold,test_schema,test_table1
tag2,table_status,hive,gold,test_schema,test_table1
```
This does not match the cardinality between the table/column and badge and can cause a lot of duplicative data in the CSV. To simplify the user experience, multiple tags can now be placed on a single row. …
> feat: Allow multiple badges on a single record for csv extracts

- example/scripts/sample_mssql_metadata.py
- example/scripts/sample_mysql_loader.py
- example/scripts/sample_postgres_loader.py
- example/scripts/sample_vertica_loader.py
Fix for https://github.com/amundsen-io/amundsen/issues/982
> fix: Add import logging to some example scripts

- example/scripts/sample_mssql_metadata.py
- example/scripts/sample_mysql_loader.py
- example/scripts/sample_postgres_loader.py
- example/scripts/sample_vertica_loader.py
- tests/unit/extractor/test_deltalake_extractor.py
> fix: fix delta lake unit test

- example/scripts/sample_mssql_metadata.py
- example/scripts/sample_mysql_loader.py
- example/scripts/sample_postgres_loader.py
- example/scripts/sample_vertica_loader.py
- setup.py
Signed-off-by: Andrew Ciambrone <andrjc4@vt.edu>
Upgrades the amundsen gremlin dependency. 
Upgrades dependency. I don't feel tests are needed. 
> chore: Upgrade dependency of Amundsen-gremlin

- databuilder/extractor/redshift_metadata_extractor.py
This updated the redshift_metadata_extractor to extract external schema as well as internal ones.
https://github.com/amundsen-io/amundsen/issues/1002
> feat: Update redshift_metadata_extractor to extract external schema

- .dependabot/config.yml
Signed-off-by: Dorian Johnson <2020@dorianj.net>
> chore: remove dependabot
