README.md

It was not mentioned anywhere as what version of python is needed to run this project. 
Most of the amundsen libraries are using 3.6+ but this one requires 2.7.x, so it would be better to mention that in Readme.md. 
Also, the readme of amundsenfrontendlibray also mentions to install this package via python3, which would fail eventually. Will update that also. 
https://github.com/lyft/amundsenfrontendlibrary#bootstrap-a-default-version-of-amundsen-using-docker (Point # 7)

Add python version as a requirement in Readme

---

databuilder/job/job.py
databuilder/task/neo4j_staleness_removal_task.py
setup.py
tests/unit/task/test_neo4j_staleness_removal_task.py

Tested in TARS.
This change is to remove stale Graph nodes and relations.
Prior to deletion it performs safety check to make sure, stale nodes/relations do not exceed defined threshold (default 5%). Once passes the safety check, it deletes 100 nodes/relations per execution.
sample job config:
>>> task = Neo4jStalenessRemovalTask()
job_config = ConfigFactory.from_dict({
'job.identifier': 'remove_stale_data_job',
'{}.{}'.format(task.get_scope(), neo4j_staleness_removal_task.NEO4J_END_POINT_KEY):
neo4j_endpoint,
'{}.{}'.format(task.get_scope(), neo4j_staleness_removal_task.NEO4J_USER):
neo4j_user,
'{}.{}'.format(task.get_scope(), neo4j_staleness_removal_task.NEO4J_PASSWORD):
neo4j_password,
'{}.{}'.format(task.get_scope(), neo4j_staleness_removal_task.STALENESS_MAX_PCT):
95, …

[DPTOOLS-1345] Delete stale nodes & relations

---

databuilder/job/job.py
databuilder/task/neo4j_staleness_removal_task.py
setup.py
tests/unit/task/test_neo4j_staleness_removal_task.py

ConfigTree.with_fallback method uses deep copy and throws exception when any object within ConfigTree is not copiable. The change is avoid doing this in job level.

Avoid using ConfigTree.with_fallback method in job level

---

databuilder/models/elasticsearch_document.py
databuilder/models/table_elasticsearch_document.py
databuilder/transformer/elasticsearch_document_transformer.py
setup.py
tests/unit/loader/test_file_system_elasticsearch_json_loader.py
tests/unit/models/test_table_elasticsearch_document.py
tests/unit/transformer/test_elasticsearch_document_transfer.py

The current ESDocument is tired to tableESDocument. This pr:
- Create a base class for ESDoc
- Move existing one to tableESDocument
This is for later added a new type for UserESDocument.

Move ESDocument to TableESDocument

---

databuilder/extractor/presto_view_metadata_extractor.py
databuilder/models/table_metadata.py
setup.py
tests/unit/extractor/test_presto_view_metadata_extractor.py
tests/unit/models/test_table_metadata.py

This PR is to add support for indexing Presto Views. Columns are sorted alphabetically.
Have tested manually and confirmed that `is_view` is an attribute of Table Node.

index presto views

---

.gitignore

Turns out `frontend` already had this: https://github.com/lyft/amundsenfrontendlibrary/blob/master/.gitignore#L25 - so we should be good on this front in all repos now

gitignore dist/ as in metadataservice PR#28

---

databuilder/models/table_metadata.py
setup.py
tests/unit/models/test_table_metadata.py

As all values pushed to neo4j by default is quoted https://github.com/lyft/amundsendatabuilder/blob/2c2b843ebd0ca08198e4940e668ea09e71335c12/databuilder/publisher/neo4j_csv_publisher.py#L333, `is_view` is changed from `bool`
to `str` as well which is not ideal.
This PR is to add custom configuration so `is_view` can be stored in neo4j as `boolean` data type.
Example: https://github.com/lyft/amundsendatabuilder/blob/37c700d9244db8dd9b65f97519eeb986d72d0d9d/databuilder/models/table_column_usage.py#L53
https://github.com/lyft/amundsendatabuilder/blob/2c2b843ebd0ca08198e4940e668ea09e71335c12/databuilder/publisher/neo4j_csv_publisher.py#L329

unquote boolean value is_view when publish to neo4j

---

example/scripts/sample_data_loader.py
setup.py

Change this line https://github.com/lyft/amundsendatabuilder/blob/v1.0.11/example/scripts/sample_data_loader.py#L177 to match the current hardcoded value in the search service at 
https://github.com/lyft/amundsensearchlibrary/blob/v1.0.0_4/search_service/config.py#L23. This means it’s backwards compatible with existing search service Docker containers etc.
Further details originally shared on the #troubleshoot Slack channel, now here as well:
————
... but, I think it's better to start figuring out how/why your ElasticSearch is failing, you want that working anyway, and debugging it will benefit everyone by hopefully eradicating a bug. What I did to make sure hostnames, ports, networking, docker containers? etc. was set up right was this:
```
curl amundsensearch:5000/search?query_term=test …
```

ES index written must match reader side

---

requirements.txt
setup.py

version 1.7.2 is throwing exception on Neo4j publisher. Reverting. Will revisit the upgrade.

Revert Neo4j Bolt upgrade

---

databuilder/publisher/neo4j_csv_publisher.py
setup.py

- Upgrade Neo4j bolt driver from 1.6.0 to 1.7.2
- Remove `tx.close()` due to the behavior change from 1.7.2 that `tx.commit()` closes the transaction and following `tx.close()` call throws exception.

[DPTOOLS-2210] Upgrade Neo4j driver to 1.7.2

---

.gitignore
databuilder/models/user.py
example/sample_data/sample_user.csv
example/scripts/sample_data_loader.py

With a bit of luck this should be able to light up the mic new /users/ pages brought by lyft/amundsenfrontendlibrary#90 
Still marked as WIP because it reverts #16 encode(utf-8) change (which I don’t understand?) - can that behavior be moved - maybe to a universal transform step? If so this PR could add that commit as well.

Add sample users to QuickStart 

---

databuilder/extractor/bigquery_usage_extractor.py
databuilder/transformer/bigquery_usage_transformer.py
example/scripts/sample_bq_usage_loader.py
requirements.txt
tests/unit/extractor/test_bigquery_usage_extractor.py
tests/unit/transformer/test_bigquery_usage_transformer.py

Implements a simple BigQuery usage transformer, reading bigquery access logs. I filter on "jobcompleted" (indicating the query finished), the timestamp and bigquery_resource. 
When a query is executed multiple times and is cached, the counter does not increase because the "referencedTables" section is then empty. In that case the BQ user gets the query results from the cache table (24 hours). But when the query changes or the underlying source tables change, the query does get executed and referencedTables has a value.
I'm following a similar approach to the Presto aggregator implementation and keep a map in memory that maintains the access of everyone.
I added two unit tests for both the extractor and transformer, yielding =~ 80% coverage rate.

Implements big query usage extractor

---

databuilder/extractor/bigquery_metadata_extractor.py
example/scripts/sample_bigquery_metadata.py
setup.py
tests/unit/extractor/test_bigquery_metadata_extractor.py

Implements the BigQuery metadata extractor. It uses Google's discovery API over the easier to use python client libraries. Extensive unit tests. Nested records are exported in dot notation ( column = 'nested.another_nest.string_col' ). 
Unit tests are in place for happy path, all possible configuration parameters and typical responses from the API with some edge cases (no tables in dataset, no datasets in project) and nested records and when a view is defined.

Implements BigQuery metadata extractor

---

databuilder/publisher/neo4j_csv_publisher.py
tests/unit/publisher/test_neo4j_csv_publisher.py

Separated Index creation step from node publish. Currently, index creation is done in the middle of node upsert enforcing publisher to commit the transaction. The change is to separate index creation step as a separate step and node publish step can have its own transaction.
This change would make publisher to have 2 passes against node file which turns out very negligible -- for 16k nodes, it just took less than 2 seconds.
Exiting unit test and performed integration test.
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License …

[DPTOOLS-2299] Separate Index creation step from Node publish

---

databuilder/extractor/bigquery_metadata_extractor.py
setup.py

The extractor wasn't tested on a dataset with > pagesize number of tables, which I noticed was failing.

[#60]: Fixes paging over dataset and column count

---

README.md
databuilder/extractor/postgres_metadata_extractor.py
example/dags/postgres_sample_dag.py
tests/unit/extractor/test_postgres_metadata_extractor.py

This PR adds support for extracting metadata from postgres. 
One slight difference from the Hive metadata extractor:
* by default, and/or when `USE_CATALOG_AS_CLUSTER_NAME` is set to `True`, the query will use the postgres db name as the cluster name
* if `USE_CATALOG_AS_CLUSTER_NAME` is `False`, *and* `CLUSTER_KEY` is specified, CLUSTER_KEY will be used as the cluster name
* if `USE_CATALOG_AS_CLUSTER_NAME` is `False`, and `CLUSTER_KEY is not specified, cluster name will fallback to 'master'
I also added a sample postgres dag (as this is how I've been doing integration testing)
added `tests/unit/extractor/test_postgres_metadata_extractor.py`, 7 tests, all passing locally
Did not add additional documentation explicitly. My hope is the sample postgres dag would function as appropriate …

Add postgres Metadata extraction support

---

databuilder/extractor/kafka_source_extractor.py
requirements.txt
setup.py
tests/unit/extractor/test_kafka_source_extractor.py

Solved https://github.com/lyft/amundsendatabuilder/issues/40
Kafka source extractor. The extractor itself is single consumer(single-threaded)
which could consume all the partitions given a topic or a subset of partitions.
It uses the "micro-batch" concept to ingest data from a given Kafka topic and
persist into downstream sink.
Once the publisher commit successfully, it will trigger the extractor's callback to commit the
consumer offset.
We are leveraging Kafka to build a push model(user push metadata to Kafka, Amundsen databuilder consumes metadata from Kafka and publish to neo4j in its own speed).
Notes: 
1. this extractor is experimental as it requires user to implement a custom transformer(like the Kafka value deserde)
2. The extractor uses single consumer ATM as we believe the …

Add an experimental Kafka source extractor

---

databuilder/models/user.py

When User model repr is called, `IndexError: tuple index out of range` error is thrown. This PR is to fix it.

Fix user model repr

---

databuilder/models/user.py
setup.py
tests/unit/models/test_table_column_usage.py

Bool value needs to be unquoted, otherwise neo4j will store the attribute as str type.

Change USER_NODE_IS_ACTIVE to unquoted

---

databuilder/models/table_metadata.py
requirements.txt
setup.py
tests/unit/models/test_table_metadata.py

Sometimes we would like the table metadata model to accept additional attributes(like URI, retention, owner, etc). This PR extends to model to store those additional attributes inside the node.

Extend TableMetadata model to accept KV pairs attributes

---

setup.py

Make confluent-kafka as optional dependency. We don't need to install confluent-kafka which brings in librdkafka if we don't use that extractor. Solved issue with https://github.com/lyft/amundsendatabuilder/issues/73

Make confluent-kafka as optional dep

---

databuilder/publisher/neo4j_csv_publisher.py
databuilder/publisher/neo4j_preprocessor.py
databuilder/task/task.py
setup.py
tests/unit/publisher/test_neo4j_csv_publisher.py
tests/unit/publisher/test_neo4j_preprocessor.py

Introducing Preprocessor that will be executed prior to relation publish. Preprocessor will run per record. 
- Added Preprocessor, DeleteRelationPreprocessor
- Changed how transaction is being committed. Previously, it committed in node publish and then committed in relation publish. Now there will be one transaction which will be only committed per requested transaction size which enables atomic publish.
Example use case: Take an example of an external privacy service trying to push personal identifiable identification (PII) tag into Amundsen. It is fine to push set of PII tags for the first push, but it becomes a challenge when it comes to following update as external service does not know current PII state in Amundsen.
The easy solution is for external service to know desired state …

Neo4j Publisher to support desired state of relation

---

databuilder/extractor/bigquery_metadata_extractor.py

Encounter this issue( google.auth.exceptions.RefreshError: ('invalid_scope: h is not a valid audience string.', u'{\n  "error": "invalid_scope",\n  "error_description": "h is not a valid audience string."\n}')) which stackoverflow shows https://stackoverflow.com/questions/48332352/google-server-to-server-oauth-error.
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License …

Update default scope to be iterable for both py2 and py3

---

databuilder/extractor/neo4j_extractor.py
databuilder/publisher/neo4j_csv_publisher.py
setup.py

Setting a idle connection timeout in Neo4j extractor which is already set in Neo4jPublisher.
Ref: https://github.com/neo4j/neo4j-python-driver/issues/205
Integration tested.
N/A

Setting idle connection timeout in neo4j_extractor

---

.gitignore
databuilder/models/application.py
example/sample_data/sample_application.csv
example/scripts/sample_data_loader.py

* This is showing Airflow as the application because Amundsen already has
the Airflow icon but it could basically be any data transformation job
e.g SQL transforming from source data set(s) to a resulting data set
(Table).
This lights up the `GENERATED BY` sidebar section visible when you navigate to http://localhost:5000/table_detail/gold/hive/test_schema/test_table1 after running 
the `python3 example/scripts/sample_data_loader.py` Quickstart loader.
At the same time this PR serves as an example of how to use the simpler of 
the Amundsen data builder `model/` classes (e.g. I think the table_stats one
would be pretty similar).
* A minor addition of a commented out line you can enable to get INFO level 
logging when running the Quickstart example data loader script.
As usual for example …

Add Quickstart sample data to demo Airflow DAG

---

databuilder/extractor/bigquery_usage_extractor.py
setup.py
tests/unit/extractor/test_bigquery_usage_extractor.py

Lots of records come from service account which ideally we should filter out. This pr provides a config to allow user to set email filtering on usage records.
2 unit tests 

Provide email filter for BQ usage extractor

---

databuilder/transformer/sql_to_table_col_usage_transformer.py
setup.py

Currently `SqlToTblColUsageTransformer` uses Threadpool just to perform timeout when ANTLR tree hits infinite loop. It turned out that Python's Threadpool internally didn't implement terminate() method and cannot be timedout. Therefore, replaced it with Pool which uses process. 
I had a concern on Pool in performance as it needs to communicate with different process but the performance difference was negligible.
Integration test done.
N/A

Replace Threadpool to Pool on SqlToTblColUsageTransformer

---

example/sample_data/sample_column_usage.csv

Fixes #27 - the problem described in https://github.com/lyft/amundsendatabuilder/issues/27#issuecomment-508583164
Manually tested using `curl localhost:5000/popular_tables/` inside the matadata service container and using the frontend UI. If a run has been done before data has been ingested to Neo4j (for example by navigating to the home page of the frontend web page) you might have to wait 11 hours for the metadata cache to be evicted. If you get tired of waiting for that you can restart the containers as the metadata cache is only in memory. 😀 
"Proof" screenshot: 
* Not easy to cover by unit test - it was only testable through integration test. The problem was bascally a combination of Quickstart sample data in `databuilder` and failed/missing understanding of spec for implementation …

Make table1 popular again

---

databuilder/extractor/postgres_metadata_extractor.py
setup.py
tests/unit/extractor/test_postgres_metadata_extractor.py

Provide a config to allow user specify database for pg extractor. In that case, we could reuse the extractor for redshift tables.

Add a flag to allow to specify database for pg extractor

---

databuilder/models/table_lineage.py
setup.py
tests/unit/models/test_table_lineage.py

Currently we don't have table lineage extractor. Provide a data model is the first step towards this goal. 
User could build a generic / specific . lineage extractor with this model.
Yes

Add table lineage model

---

databuilder/transformer/regex_str_replace_transformer.py
setup.py
tests/unit/transformer/test_regex_str_replace_transformer.py

The current regex string transformer will fail if a None value is provided.  This makes it difficult to use for data that is optional.  In particular, we weren't able to use it for column descriptions because not all columns have descriptions.
I added a check for None and exited early if the value matched None.  In addition, I added a check to make sure the value was not numerical.
I added unit tests test to make sure that numeric and None values are ignored for the regex transformer.
I confirmed that the numeric change would not cause an unintended regression by running the unit test and confirming it caused an AttributeError on the val.replace method call. 
I made a change to python doc that outlined the new rules that ignored.
Make sure you have checked **all** steps below to ensure a …

Check for a valid string on the regex transformer.

---

databuilder/models/hive_watermark.py
databuilder/models/watermark.py
example/sample_data/sample_watermark.csv
example/scripts/sample_data_loader.py
setup.py
tests/unit/models/test_watermark.py

Sample quickstart data enriched with table watermarks info (oldest & latest partitions).
Also HiveWatermark class redesigned to handle any DB type watermarks.
No new tests. Existing tests for watermarks have been updated.
No new documentation.
Displayed watermark data example:

Add sample high/low watermark data to quick start (#62)

---

databuilder/models/table_owner.py
example/sample_data/sample_table_owner.csv
example/scripts/sample_data_loader.py
tests/unit/models/test_table_owner.py

Sample quickstart data for table owners (and possibility of ingestion custom data using `sample_table_owner.csv` file).
TableOwner init method API changed to accept both `List` and comma-separated `str` of owners.
Existing TableOwner test has been extended.
No new documentation.
closes lyft/amundsen#139

Add sample table owner data to quick start (#139)

---

databuilder/models/table_metadata.py
example/sample_data/sample_table.csv
example/scripts/sample_data_loader.py
setup.py
tests/unit/models/test_table_metadata.py

Sample table tag data for quickstart: slightly changed TableMetadata API and sample table data.
Also removed "Add owners" TODO item because now this data is being ingested using TableOwners model.
TableMetadata unit tests extended to cover a new init scenario.
closes lyft/amundsen#129

Add sample table tag data to quickstart

---

databuilder/extractor/bigquery_metadata_extractor.py
setup.py

Currently the key path may not be available as a file, we should support the case if the credential is pass as a string.
This is supported per gcp doc(https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html).

Allow credential pass from conf variable for BQ extractor

---

databuilder/models/table_metadata.py
setup.py
tests/unit/models/test_table_metadata.py

Fixed empty tags appearance issue.
Provided additional unit tests for empty List/str of tags.
Then reorganized TestTableMetadata because of flake8 exception:
[C901] 'TestTableMetadata.test_serialize' is too complex (12)
closes lyft/amundsen#148

Prevent empty table tags appearance

---

README.md
databuilder/extractor/glue_extractor.py
requirements.txt
tests/unit/extractor/test_glue_extractor.py

Add an AWS Glue Extractor
It was add another test file to this new extractor based on the `test_hive_table_metadata` file
I documented the code functions and added an example on README to follow others extractors example

Add an AWS Glue Extractor

---

databuilder/extractor/snowflake_metadata_extractor.py
tests/unit/extractor/test_snowflake_metadata_extractor.py

For the Snowflake metadata extraction added is_view parameter in TableMetadata to capture views correctly.

Fixed Snowflake views being captured as tables

---

databuilder/models/application.py
example/sample_data/sample_application.csv
example/scripts/sample_data_loader.py
setup.py
tests/unit/models/test_application.py

Update the Application model to be more generic.
Currently it assume the task_id format to be `hive.schema_name.table_name` which is not always the case. Extend it to be more generic.

Update Application model to be more generic

---

README.md
databuilder/extractor/glue_extractor.py

- `glue_extractor` scope refactored to `glue` since there is already `extractor` on the config dict
- AWS filters option added to support only extracting certain tables based
I didn't added any tests since I am abstracting the search function (there is not any good aws glue mock in python)
I added a sample job config and more lines explain about the code.

GlueExtractor refactor

---

databuilder/extractor/bigquery_usage_extractor.py
tests/unit/extractor/test_bigquery_usage_extractor.py

In practice, when requesting logs going back more than a few days, the
StackDriver API sometimes responds with an empty page with a next page
cursor. After polling the next page a few times you eventually start
getting entries. The empty pages have no `entries` key, which previously
resulted in a KeyError.
This change allows the extractor to continue polling instead of blowing up.
Added a simple test with a mocked out response with no entries that fails with `KeyError` if the guard clause is not present.
No doc changes required.
- All the public …

BigQuery Usage Extractor: Guard against log entry pages not containing 'entries' key

---

databuilder/extractor/postgres_metadata_extractor.py

Since the Postgres Metadata Extractor logged the sql statement right after formatting it with the `cluster_source` and `where_clause_suffix` if we override the sql statement through `'extractor.postgres_metadata.extractor.sqlalchemy.{}'.format(SQLAlchemyExtractor.EXTRACT_SQL)` it would work but it would log the wrong statement
I didn't add any tests since testing what the logger is printing is not that simple (or maybe it is) and it wouldn't be something valuable to test (always open to discuss it)

Postgres Metadata Extractor logger fixed

---

databuilder/extractor/bigquery_watermark_extractor.py

Use configuration parameter for Google Cloud project_id instead of hardcoded.
Use project_id config instead of hard coded value in BigQuery Watermark extractor.
Obvious fix. Requires integration to Google Cloud to test.
- [x ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [ x] PR includes a summary of changes. 
- [ x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ x] In case of new functionality, my PR adds documentation …

Use config parameter for project_id

---

databuilder/task/task.py

When transformer returned null no more records is processed, this means a transformer cannot filter out data. It also mean the task silently skip process rest of the records.
When transformer returned null no more records is processed, this means a transformer cannot filter out data. It also mean the task silently skip process rest of the records.
No tests exist for this part of the code
N/A

Fix task stop prematurely if transformer return None

---

databuilder/extractor/base_bigquery_extractor.py

It uses the right class constant to get the const for the scopes, it was working well for the metadata, but not for the usage
No test where needed

fix: Use the right scope constant to get bigquery table usage

---

databuilder/extractor/bigquery_usage_extractor.py

`DELAY_TIME` was an undefined constant previously. This patch makes
delay timeout configurable using a config param.
Default of 100 seconds as API request quota limits are guaranteed to be
refilled after said time interval accoring to the documentation at:
https://cloud.google.com/compute/docs/api-rate-limits
A better alternative would be an exponential backoff mechanism.
No changes.
No documentation changes.

Fix API throttle handling in BigQueryTableUsageExtractor

---

databuilder/loader/file_system_csv_loader.py
databuilder/loader/file_system_elasticsearch_json_loader.py

This will prevent an exception from being thrown if, somehow, a file was not opened in the first place. I hit this when debugging something else. I am still digging into why it happened. 
I did not change any tests. If you see any, let me know. 
None. I don't this this deviates from the documented behavior. 

Adding an if statement to prevent an exception when closing a file that is not opened

---

example/dags/postgres_sample_dag.py

The original example script couldn't read my PostgreSQL column metadata. I found that there was a problem with the `where_clause_suffix` variable.
No changes
No documentation changes

Made changes to where_clause_suffix to read PostgreSQL column metadata

---

databuilder/models/table_metadata.py
example/sample_data/sample_table.csv
example/sample_data/sample_tags.csv
example/scripts/sample_data_loader.py

Standardized tag parsing from serialized tag strings. Allowed for tag badges. I made the choice of choosing ^b to represent that a tag string is a badge. 
For example, `pii` would be normal tag. `pii^b` would be a badge.
Added __repr__ for TagMetadata
Modified ColumnMetadata __repr__
Added badges and isView to sample data
Switched sample data loader to use CSVTableColumnExtractor
Added unit test for CSVTableColumnExtractor
Modified existing table model tag test to test for badges.
Only sample data modified at this time. In separate commit to base amundsen repo, will add screenshot posted here assuming this MR gets merged.
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party …

Issue 208/adding badge quickstart withcol

---

databuilder/models/standalone_column_model.py

Fixes sort order when using standalone column model.
NOTE: I wonder if standalone column model should be deprecated or refactored so that it doesn't get out of sync with other column model? If primary purpose is for sample data loader, there is a different approach that we can take.
None
None

adding UNQUOTED_SUFFIX to sort_order

---

databuilder/models/table_metadata.py
example/sample_data/sample_col.csv
example/sample_data/sample_table.csv
example/sample_data/sample_table_programmatic_source.csv
example/scripts/sample_data_loader.py
setup.py
tests/unit/extractor/test_bigquery_metadata_extractor.py
tests/unit/extractor/test_csv_extractor.py
tests/unit/models/test_table_metadata.py

Issue: https://github.com/lyft/amundsen/issues/147
Goal: To add a new node to the data model called "ProgrammaticDescription" which allows for an arbitrary number of descriptions that would be populated programmatically. This would simplify the process of allowing different data feeds that are company specific or that require huge blocks of text without having to give up the ability for users to edit the table description.
At this time, this was only introduced for tables. Likely there is no need for this for columns as there is already a similar concept "column stats".
This set of changes does not include these nodes in search, I have another branch with search changes that I will put up for MR after this first set of MR's are approved.
There are other MRs for other services here: …

Issue 147/ Programmatic Documentation Notes

---

databuilder/models/table_metadata.py
setup.py

Constant `DESCRIPTION_NODE_LABEL` previously available changed location by [PR](https://github.com/lyft/amundsendatabuilder/pull/187) This PR is to make it available again.
Integration tested
N/A

Patch to fix backward incompatible issue on table metadata

---

databuilder/publisher/neo4j_csv_publisher.py
setup.py

We have a table with a description of `¯\_(ツ)_/¯` and neo4j doesn't like that backslash.
This will escape backslashes.
There isn't a test for escaping quotes and I am not sure what the best way to write that test would be.
I believe this behavior is expected and shouldn't need documentation. 

escaping backslashes in neo4j publisher

---

example/sample_data/sample_table_programmatic_source.csv
example/sample_data/sample_user.csv
example/scripts/sample_data_loader.py

Currently, `sample_data_loader.py` is bugged. Therefore, I made some fixes.
This PR mostly changed `schema_name` -> `schema` and `name` -> `full_name`.
If you run `sample_data_loader.py` on the latest branch without making any changes, it will return this error.
```
Traceback (most recent call last):
File "example/scripts/sample_data_loader.py", line 643, in <module>
load_table_data_from_csv('sample_table_programmatic_source.csv', 'programmatic')
File "example/scripts/sample_data_loader.py", line 89, in load_table_data_from_csv
i['description_source']) for i in dr]
File "example/scripts/sample_data_loader.py", line 89, in <listcomp>
i['description_source']) for i in dr]
KeyError: 'schema'
```
No need for either since this only changes example scripts.
Make sure you have checked **all** …

Fix Sample Scripts and Data

---

databuilder/extractor/hive_table_metadata_extractor.py
databuilder/extractor/presto_view_metadata_extractor.py
setup.py
tests/unit/extractor/test_hive_table_metadata_extractor.py

The recent refactor to 2.0.0 causes the HiveTableMetadataExtractor to fail:
https://github.com/lyft/amundsendatabuilder/commit/dac8110d333f6dbc0e0f40c8d9c5e152ffa43775
It appears to be because `schema` is a reserved keyword in my Hive metastore.  
Modified `test_hive_table_metadata_extractor.py`.
None.

Fix broken HiveTableMetadataExtractor.

---

databuilder/extractor/neo4j_search_data_extractor.py
databuilder/models/table_elasticsearch_document.py
databuilder/publisher/elasticsearch_publisher.py
requirements.txt
tests/unit/extractor/test_neo4j_extractor.py
tests/unit/loader/test_file_system_elasticsearch_json_loader.py
tests/unit/models/test_table_elasticsearch_document.py
tests/unit/publisher/test_elasticsearch_publisher.py

Adds badges to elastic search results so that they can be surfaced by the search service. End goal is to allow badges to be visible on search results page. 
Modified tests to include badges as a field for tables from elastic search 
N/A

Add badges to Neo4jExtractor and elastic search 

---

databuilder/models/dashboard/dashboard_table.py
setup.py
tests/unit/models/dashboard/test_dashboard_table.py

Add a model to capture dashboard<->tables lineage. The model only creates relationship and not nodes.
And it is a 1:N between dashboard and tables.
There are a few ways to get dashboard and those tables used by the dashboard:
-  API from the product(e.g mode analytics doesn't, looker, tableau, even superset) that directly provides which tables used by the charts of the given dashboard.
- API that provides sql that powers the charts of the given dashboard which requires user to parse the sql to get the table name.
- An internal table to store this metadata. At Lyft whenever a query was run in mode dashboard, it will get captured in presto query log which parsed and stored the table id for a given dashboard. This is similar to the second case. 
Hence Amundsen only provides the model and …

Add Dashboard Table model

---

databuilder/extractor/neo4j_search_data_extractor.py
tests/unit/extractor/test_neo4j_search_data_extractor.py

As we removed the dashboard search extractor(https://github.com/lyft/amundsendatabuilder/pull/219) due to its duplication, we provide the search default query for user/dashboard here.
Provide a new config to allow user select different cypher query.

Add default cypher query for user/dashboard entity to search extractor

---

databuilder/extractor/dashboard/mode_analytics/mode_dashboard_extractor.py
databuilder/extractor/dashboard/mode_analytics/mode_dashboard_usage_extractor.py
databuilder/loader/generic_loader.py
setup.py
tests/unit/loader/test_generic_loader.py

Added:
- ModeDashboardUsageExtractor that extracts accumulated view count of dashboard
- GenericLoader that calls back a function that user provided. In Lyft, we will publish accumulated view count back to our Hive/Presto ecosystem and take daily snapshot so that we can calculated delta view count.
Unit test is added. Integration test has been done.
docstring

Adding Mode dashboard usage extractor and generic loader

---

databuilder/models/user.py
tests/unit/models/test_table_column_usage.py
tests/unit/models/test_user.py

Frontend seems to name this field as `role_name`. Despite our user endpoint uses title, we will stick with role_name instead to avoid the conversion.

Slight change from title to role name

---

README.md
databuilder/task/neo4j_staleness_removal_task.py
setup.py
tests/unit/task/test_neo4j_staleness_removal_task.py

Added:
- TTL based stale data removal on Neo4jStalenessRemovalTask
- Dry run on Neo4jStalenessRemovalTask
Unit tests have been added. Performed integration tests.
Updated README.md
docstring

Stale removal via timestamp

---

README.md

Cf. issue https://github.com/lyft/amundsen/issues/348
The last sentence of readme was:
> To see in action, take a peek at [ModeDashboardExtractor](//github.com/lyft/amundsendatabuilder/blob/master/databuilder/extractor/dashboard/mode_dashboard_extractor.py)
The link was dead. I updated it with what seemed to be the right one: https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_extractor.py

repairing link to ModeDashboardExtractor in README

---

databuilder/models/application.py

I was unable to get Airflow databuilder loads working for my own tables, but was able to load them with the sample loader script.  I realized that the sample loader is always defaulting to the "gold" cluster, and so was databuilder, but my own tables were in a different cluster.  This removed the hard-coded cluster and makes it an option.
More discussion at https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1588011296187400
- In case you are adding a …

Remove hard-coded cluster fromt the Application model

---

README.md
databuilder/extractor/dashboard/mode_analytics/mode_dashboard_extractor.py
databuilder/models/application.py
databuilder/rest_api/mode_analytics/mode_paginated_rest_api_query.py
databuilder/rest_api/rest_api_query.py
setup.py
tests/unit/rest_api/mode_analytics/test_mode_paginated_rest_api_query.py

Added `ModePaginatedRestApiQuery` that extends `RestApiQuery` to support pagination
Unit test done. 
Found integration testing on the space that has lots of pages. Some how it currently returning `500` server side error on `104`th page and currently waiting from Mode support's response.
Updated doc to add link to `ModePaginatedRestApiQuery` for the example of pagination.

Add support for pagination on Mode list reports on space API

---

databuilder/loader/file_system_neo4j_csv_loader.py
setup.py

Fix `UnicodeEncodeError: 'ascii' codec can't encode character '\x91' in position 147: ordinal not in range(128)` when the csv loader used in py3.

Support unicode for file system neo4j csv loader in py3

---

databuilder/extractor/neo4j_search_data_extractor.py
setup.py

Previously, `last_successful_run_timestamp` was empty string when missing ends up failing in search service. Fixing the extraction query to cast it to Int and it will return `None` when missing and it's proper behavior.
Integration test.
N/A

fix: Cast int on last_successful_run_timestamp on Dashboard search extraction

---

databuilder/publisher/elasticsearch_constants.py
setup.py

So the change got more pushed back internally.  Let's revert it for now.

fix: revert default search mapping change

---

README.md
databuilder/extractor/neo4j_extractor.py
databuilder/publisher/neo4j_csv_publisher.py
databuilder/task/neo4j_staleness_removal_task.py
docs/dashboard_ingestion_guide.md
example/scripts/sample_data_loader.py
tests/unit/publisher/test_neo4j_csv_publisher.py
tests/unit/task/test_neo4j_staleness_removal_task.py

Starting with Neo4J v4, it no longer auto generates SSL/TLS
certificates if they aren't supplied. To keep the example
working, I needed config to specify whether the connection
to Neo4J should be encrypted or not.
~It defaults to False, at the moment, so I think most
people would need to add an explicit True to their config.~
The previous behavior was to assume encryption, so the default in this commit is also to assume encryption. (I had changed the default in this PR from False to True in a later commit after opening the PR.)
There are complimentary changes to `amundsenmetadatalibrary` and `amundsen` that I will put in to other PRs:
* https://github.com/lyft/amundsenmetadatalibrary/pull/139
* For amundsen, I'll wait to raise the PR until a tagged docker image of …

Compatibility with Neo4J 4.0.4 (4.x in general should work)

---

README.md
databuilder/extractor/dashboard/mode_analytics/mode_dashboard_user_extractor.py
databuilder/models/user.py
databuilder/transformer/remove_field_transformer.py
requirements.txt
setup.py
tests/unit/models/test_user.py
tests/unit/transformer/test_remove_field_transformer.py

Ingest Mode Analytics user. In order to access control Mode dashboard's preview, Amundsen needs to verify if user is registered in Mode. This PR is to ingest mode user_id so that Amundsen could know (through metadata service API) if user is registered in Mode or not.
Added: 
- ModeDashboardUserExtractor: Extracts `mode_user_id` and update User node
- RemoveFieldTransformer: Remove any requested fields from Dict. (so that User node won't add unnecessary attributes)
Updated unit test. Performed integration test.
Updated README.md
- All the public functions …

feat: Ingest Mode Analytics user

---

.travis.yml
README.md
setup.py

Reverts lyft/amundsendatabuilder#280
(Lyft internally still needs python2.7 artifact in Pypi).

fix: Revert "ci: remove py2 ci"

---

README.md
databuilder/extractor/snowflake_metadata_extractor.py
example/scripts/sample_data_loader.py
example/scripts/sample_snowflake_data_loader.py
tests/unit/extractor/test_snowflake_metadata_extractor.py

This is a proposed fix for the bug described in https://github.com/lyft/amundsen/issues/494 - it adds a new configuration key, SNOWFLAKE_DATABASE_KEY, and uses it to set the database that metadata should be extracted from.  The DATABASE_KEY reverts back to simply describing the database, with a default of 'snowflake'.
Added some new tests for a simple data load that checks changing the database name.
Updated the README to reference the new config name.

fix: Set snowflake extractor database to be consistent with other extractors

---

databuilder/extractor/neo4j_search_data_extractor.py
example/scripts/sample_data_loader.py

Added `role_name` to `Neo4jSearchDataExtractor.DEFAULT_NEO4J_USER_CYPHER_QUERY`.
This field was added to the ES document in #232, but it was not added to the default query in the `Neo4jSearchDataExtractor`. Consequently, attempts to use the default query would fail.
This change renders it unnecessary to hardcode the user query for a basic Neo4j to ElasticSearch load, as in `sample_data_loader.py`.
N/A: Just a string change in `Neo4jSearchDataExtractor`. `sample_data_loader.py` has no unit tests, but manually running works as expected.
N/A
- All the …

fix: Added role_name to defaut user query in Neo4jSearchDataExtractor

---

requirements.txt

Freeze the version of pytest-cov due to the conflict with pytest
`pytest-cov 2.10.0 has requirement pytest>=4.6, but you'll have pytest 3.10.1 which is incompatible.
`
Failing build: https://travis-ci.com/github/lyft/amundsendatabuilder/jobs/349937443
Passes build.
N/A

fix: Update pytest-cov>=2.5.1,<=2.9

---

databuilder/extractor/dashboard/mode_analytics/mode_dashboard_extractor.py

Change the Mode dashboard URL based on organization name passed in the config.
None, I didn't see tests for dashboards yet.
None

fix: Variable organization in Mode URL

---

README.md
databuilder/extractor/neo4j_search_data_extractor.py
databuilder/models/table_metadata.py
databuilder/transformer/table_tag_transformer.py
tests/unit/transformer/test_table_tag_transformer.py

This was a use case that came up for us several times, where we want all tables loaded from a specific source to have the same tag.  This transformer makes it easy to add a tag independent of what the extractor is doing.
It seems like none of the other transformers have tests, so I was not sure what pattern to follow.
No new docs, hopefully the transformer is simple enough to be self explanatory.

feat: Add a transformer that adds tags to all tables created in a job

---

setup.py

Currently for 2.6.3 latest version, we have the following error:
```
ERROR: pytest-cov 2.10.0 has requirement pytest>=4.6, but you'll have pytest 3.10.1 which is incompatible.
```
This has been fixed by @jinhyukchang 's change. We just need to release a new version to pypi.
- All the public functions and the classes in the PR contain docstrings that …

ci: release new version to pickup pytest fix

---

databuilder/publisher/neo4j_csv_publisher.py

This is basically a re-do of #191.
`Neo4jCsvPublisher` currently imports data by crafting Cypher queries through string building. Problems occur in string literals when the original strings contain backslashes: literal values like `\n` would be converted to a newline, while a literal that is not a valid escape sequence (e.g., `\_`) will result in an error decoding the Cypher query.
This issue was identified and addressed in #191, but the final, accepted fix doesn't actually do anything. The confusion seems to stem from the way Python outputs string literals in a REPL-like environment:
```
>>> '\\'
'\\'
>>> print('\\')
\
>>> '\_'
'\\_'
>>> '\_'.replace("\\", "\\") # the accepted fix from #191
'\\_'
>>> print('\_'.replace("\\", "\\")) # note: this didn't really work!
\_
>>> …
```

fix: Escape backslashes in Neo4jCsvPublisher

---

databuilder/publisher/neo4j_csv_publisher.py

I have to come clean: I never tested the change in #291. It seemed like an obvious fix, but this is actually a regression. Any string with a single quote in it will now break the publisher. (Sorry!)
The escaping of backslashes needs to happen *before* the escaping of quotes. The reason for this is obvious (in retrospect). Consider the following:
`O'Brien` --(escape quote)--> `O\'Brien` --(escape backslash)--> `O\\'Brien`
Put this in quotes, and you get a problem: `'O\\'Brien'`
This PR changes the order so that backslashes are escaped first:
`O'Brien` --(escape backslash)--> `O'Brien` --(escape quote)--> `O\'Brien` (much better)
So now quotes should work fine again, and backslashes should actually work too (which was the point of both #191 and #291):
`c:\users\o'brien` --(escape …

fix: Escape backslashes before quotes in Neo4jCsvPublisher

---

docs/models.md

Updated the contents of `docs/models.md` and fix a malformed link to the implementation of the `dashboard_execution` model.
None needed, only updates documentation
Updated the contents of `docs/models.md` and fix a malformed link to the implementation of the `dashboard_execution` model. I could not find any documentation about how to build the docs locally to test (I assume because you're using GitHub pages) but I tested on my fork and the relative link worked when I followed it through the GitHub UI, whereas it did not before.
- All the public functions …

fix: Fix broken doc link to dashboard_execution model

---

example/dags/hive_sample_dag.py

This solves https://github.com/lyft/amundsen/issues/550
1. Added missing column "database" since HiveWatermark is not used anymore
2. Put both "database" and "schema" column names under blockquotes, as those are reserved keywords
Example code, no tests. Manually verify by running with docker-compose.

fix: sql for missing columns and mysql based dialects (amundsen#550)

---

example/dags/hive_sample_dag.py

[FIX]
Running "create_table_metadata_databuilder_job()" was giving an Exception : 
""ConfigMissingException" : No Configuration setting found for key job_publish_tag."
Hence,
Adding a missing key for job_publish_tag in "create_table_metadata_databuilder_job()" of hive_sample_dag.py.
Ran the modified function and checked neo4j for the graphs. They were being built.
None

fix: Added missing job tag key in hive_sample_dag.py

---

databuilder/task/neo4j_staleness_removal_task.py
tests/unit/task/test_neo4j_staleness_removal_task.py

Fixed the cypher statement param issue happening in Neo4jStalenessRemovalTask due to which statements were not returning any results in the case when we determining staleness using milliseconds and published timestamp. 
A detailed description is mentioned in this issue https://github.com/lyft/amundsen/issues/567
Modified the tests for test_neo4j_staleness_removal_task.py according to the change in params for the cypher statement

fix: cypher statement param issue in Neo4jStalenessRemovalTask

---

.travis.yml
Makefile
README.md
databuilder/__init__.py
databuilder/callback/call_back.py
databuilder/extractor/db2_metadata_extractor.py
databuilder/extractor/mssql_metadata_extractor.py
databuilder/extractor/mysql_metadata_extractor.py
databuilder/extractor/postgres_metadata_extractor.py
databuilder/extractor/snowflake_metadata_extractor.py
databuilder/loader/file_system_neo4j_csv_loader.py
databuilder/models/neo4j_csv_serde.py
databuilder/models/table_metadata.py
databuilder/publisher/neo4j_csv_publisher.py
databuilder/publisher/neo4j_preprocessor.py
databuilder/rest_api/base_rest_api_query.py
databuilder/rest_api/rest_api_failure_handlers.py
databuilder/transformer/regex_str_replace_transformer.py
setup.py
tests/unit/publisher/test_elasticsearch_publisher.py

Remove all direct usage of `six` (must stay in requirements because other packages still use it), remove python 2 CI.
Ref: https://github.com/lyft/amundsen/issues/560
Removed Python 2 from CI suite, but no tests modified.
README updated to reflect new requirements.
cc @feng-tao

chore: remove python2

---

databuilder/extractor/hive_table_metadata_extractor.py
tests/unit/extractor/test_hive_table_metadata_extractor.py

This pr is to fix https://github.com/lyft/amundsen/issues/552 which allows user to provide hive metastore sql.
yes. add a unit test to test the new config.

feat: allow hive sql to be provided as config

---

tests/unit/extractor/test_bigquery_metadata_extractor.py
tests/unit/extractor/test_bigquery_usage_extractor.py
tests/unit/extractor/test_bigquery_watermark_extractor.py

Without this, tests will by default fail in a local environment because there are no Google credentials present.
Not sure why Travis was working before; if dev/CI parity is important to us, I'm happy to investigate to make it need this as well.
n/a
n/a

tests: add mock for bigquery auth

---

.travis.yml

Updated repo name in travis file

ci: Change repo name in travis file

---

requirements.txt

This fixes the issue with the attrs transitive dependency described in #331 (unpinning dependencies generally), without touching everything else. I created this PR since I was unable to get #331 to pass CI.
I noticed that #329 (upgrading attrs) would also fix my problem, but I think unpinning is better.

fix(deps): Unpin attrs

---

.travis.yml
tests/unit/extractor/test_hive_table_last_updated_extractor.py
tests/unit/rest_api/mode_analytics/test_mode_paginated_rest_api_query.py

ref: https://github.com/amundsen-io/amundsen/issues/606
Python 3.7 introduced breaking changes involving generators and `StopIteration`, which broke two of our tests. As far as I can tell, no actual functionality was broken.
Fix the tests, and enable 3.7 in CI.
Comments in commit messages for the trickier one
n/a
cc @feng-tao

build: fix broken tests in Python 3.7, test in CI

---

example/dags/postgres_sample_dag.py

Update postgres_sample_dag to make elasticsearch publisher run after table extract job has completed.
- [] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [] In case of new functionality, my PR adds documentation that describes how to use it.

Update postgres_sample_dag to set table extract job as upstream for elasticsearch publisher

---

example/dags/athena_sample_dag.py

Made couple of changes to Athena sample DAG. 
- PythonOperators in the DAG were not initialized properly. Fixed the DAG creation and set the dag structure explicitly
- Renamed the Task Names to be consisted with other sample dags
- Removed unused kwargs in method call. 

Fix Athena sample DAG

---

example/dags/hive_sample_dag.py
example/dags/postgres_sample_dag.py

Signed-off-by: Alagappan Sethuraman <alagappan.als@gmail.com>
Fixed couple of minor things in Sample Dags - removed unused kwargs params, renamed airflow tasks and set dag structure explicitly

Sample dags minor cleanup

---

setup.py

This is my second attempt to solve the problems described in #331, since #332 didn't really go far enough.
Essentially, this solves the problem by simply no longer forcing the CI requirements on the package itself.
The thing is, this somewhat skirts the issue... the change is basically untested, since the requirements in CI are the same. The difference is that the requirements _in general_ are looser now.
We could also start removing some of the requirements in requirements.txt but having see #127 I understand now (I think) that these files are used internally at Lyft - if that's correct then it would make sense that we can't really mess with them. However, perhaps we could use a different requirements file for CI? …

fix(deps) Stop importing requirements.txt into setup.py

---

databuilder/extractor/dashboard/tableau/tableau_dashboard_constants.py
databuilder/extractor/dashboard/tableau/tableau_dashboard_extractor.py
databuilder/extractor/dashboard/tableau/tableau_dashboard_last_modified_extractor.py
databuilder/extractor/dashboard/tableau/tableau_dashboard_query_extractor.py
databuilder/extractor/dashboard/tableau/tableau_dashboard_table_extractor.py
databuilder/extractor/dashboard/tableau/tableau_dashboard_utils.py
databuilder/extractor/dashboard/tableau/tableau_external_table_extractor.py
example/scripts/sample_tableau_data_loader.py
tests/unit/extractor/dashboard/tableau/test_tableau_dashboard_extractor.py
tests/unit/extractor/dashboard/tableau/test_tableau_dashboard_last_modified_extractor.py
tests/unit/extractor/dashboard/tableau/test_tableau_dashboard_query_extractor.py
tests/unit/extractor/dashboard/tableau/test_tableau_dashboard_table_extractor.py

When executing the Tableau extractor in different environments (development, production, etc), we saw the need to have different URLs and protocols depending on connectivity. For example, our airflow server that runs the extractor routes to the Tableau server via port 80 and a specific IP address.
To allow for the most configurability, this PR opens up 2 values:
* `API_BASE_URL` - Protocol+Host for API calls
* `TABLEAU_BASE_URL` - Protocol+Host for links on the Dashboard Detail page (eg. "Open Dashboard" button)
`TABLEAU_HOST` has been removed in favor of these.
Added new configs to tests.
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License …

fix: Set Tableau URLs (base + API) via config

---

README.md
databuilder/extractor/snowflake_table_last_updated_extractor.py
tests/unit/extractor/test_snowflake_table_last_updated_extractor.py

Related issue : https://github.com/amundsen-io/amundsen/issues/664
Adding a new extractor to extract table last updated timestamp for tables in Snowflake.
Added new unit test `test_snowflake_last_updated_timestamp_extractor.py` to improve coverage.
Updated the README.md file to update extractor list and added some notes on how to use the new extractor

feat: Add Snowflake table last updated timestamp extractor

---

example/scripts/sample_mysql_loader.py

This PR adds a MySQL sample data loader similar to the sample Postgres loader (almost everything is the same from that loader save the metadata extractor and the config settings).
Here's the diff between files:
<details> <summary>File Diff</summary>
```
17c17
< from databuilder.extractor.postgres_metadata_extractor import PostgresMetadataExtractor
---
> from databuilder.extractor.mysql_metadata_extractor import MysqlMetadataExtractor
57,59c57,59
<     port = '5432'
<     db = 'postgres'
<     return "postgresql://%s@%s:%s/%s" % (user, host, port, db)
---
>     port = '3306'
>     db = 'mysql'
>     return "mysql://%s@%s:%s/%s" % (user, host, port, db)
62c62
< def run_postgres_job():
---
> def run_mysql_job():
64c64
<         where table_schema = 'public'
---
>         where c.table_schema …
```

feat: Add MySQL sample data loader

---

databuilder/extractor/base_postgres_metadata_extractor.py
databuilder/extractor/postgres_metadata_extractor.py
databuilder/extractor/redshift_metadata_extractor.py
tests/unit/extractor/test_postgres_metadata_extractor.py
tests/unit/extractor/test_redshift_metadata_extractor.py

Splits `PostgresMetadataExtractor` into `BasePostgresMetadataExtractor`, `PostgresMetadataExtractor` and `RedshiftMetadataExtractor` (the latter two inherit from `BasePostgresMetadataExtractor`).
This allows us to safely modify the `SQL_QUERY` constant for Redshift-based deployments to pull late binding views into Amundsen.
See https://github.com/amundsen-io/amundsen/issues/672
I'm happy to write tests once folks are happy with the general structure of the PR (this is my first time contributing :) ).
My understanding is that I should be adding a new test for the `RedshiftMetadataExtractor` similar to what we have currently for the `PostgresMetadataExtractor`.
I'm happy to update documentation once folks are happy with the general structure of the PR (this is my first time contributing :) …

fix: "PostgresMetadataExtractor doesn't discover Redshift late binding views"

---

README.md
databuilder/extractor/dashboard/mode_analytics/batch/__init__.py
databuilder/extractor/dashboard/mode_analytics/batch/mode_dashboard_charts_batch_extractor.py
databuilder/extractor/dashboard/mode_analytics/mode_dashboard_constants.py
databuilder/extractor/dashboard/mode_analytics/mode_dashboard_utils.py
tests/unit/extractor/dashboard/mode_analytics/__init__.py
tests/unit/extractor/dashboard/mode_analytics/batch/__init__.py
tests/unit/extractor/dashboard/mode_analytics/batch/test_mode_dashboard_charts_batch_extractor.py

Leverage the latest mode discovery API(https://mode.com/help/articles/discovery-api/) which is much more performant than the previous version. Feel free to check out mode's blog post(https://mode.com/blog/new-features-to-help-you-manage-users-and-discover-data-at-scale/)
Previous mode chart legacy API doesn't work as it doesn't return the full data.
yes with Lyft staging as well
yes

feat: Mode Batch dashboard chart extractor using discovery API

---

example/sample_data/sample_table_programmatic_source.csv

Resolves amundsen-io/amundsen#674
See the details of the above issue for more context. Essentially the newline characters present in this data were being read in as two separate characters, while having them as literal newlines in the source fill allows python to correctly interpret the fields without any additional ingestion settings. 
Since this is sample data I didn't modify any tests, though I did test the ingestion myself locally.
None

fix: Sample programmatic source data

---

databuilder/extractor/neo4j_search_data_extractor.py

Updated queries to get Badges rather than Tags with badge type on neo4j.
N/A
N/A

feat: Updating badges to not be tags

---

README.md
databuilder/extractor/user/__init__.py
databuilder/extractor/user/bamboohr/__init__.py
databuilder/extractor/user/bamboohr/bamboohr_user_extractor.py
requirements.txt
tests/unit/extractor/user/__init__.py
tests/unit/extractor/user/bamboohr/__init__.py
tests/unit/extractor/user/bamboohr/test_bamboohr_user_extractor.py
tests/unit/resources/extractor/user/bamboohr/testdata.xml

Add a new extractor for pulling user information (team, role, email address, name from BambooHR)
Yep!  There's a simple new test that mocks the HTTP request to BambooHR's API and checks that the XML parsing logic is working as expected.
No new documentation added.  Happy to add some if folks point me in the right direction.

feat: Add an extractor for pulling user information from BambooHR

---

databuilder/extractor/dremio_metadata_extractor.py
example/scripts/sample_dremio_data_loader.py
setup.py
tests/unit/extractor/test_dremio_metadata_extractor.py

The PR adds a Dremio extractor object along with sample usage and tests. The primary file added is: 
`databuilder/extractor/dremio_metadata_extractor.py`
No new dependency was added. This appears to be in line with the de facto standard of not adding extractor dependencies explicitly to the library's `requirements.txt` file. (e.g. the Big Query extractor raises a `ModuleNotFoundError` unless the user explicitly add the dependencies required by the extractor) Please let me know if this is an issue.
A new test was created for the above file:
`tests/unit/extractor/test_dremio_metadata_extractor.py`
No other test modifications are present.
Doc strings are present, but the following example was also provided:
`example/scripts/sample_dremio_data_loader.py`
Make sure you have checked **all** …

feat: Dremio extractor

---

databuilder/publisher/elasticsearch_constants.py
databuilder/publisher/elasticsearch_publisher.py
docs/dashboard_ingestion_guide.md
example/scripts/sample_data_loader.py
example/scripts/sample_tableau_data_loader.py
requirements.txt
setup.py

Reverts amundsen-io/amundsendatabuilder#385
Reverting because marshmallow >v3.0 is not compatible with marshmallow-annotations, will deprecate annotations dep to fix.

fix: Revert "refactor: Update ES index maps to use same maps of amundsen-common"

---

databuilder/extractor/hive_table_metadata_extractor.py
tests/unit/extractor/test_hive_table_metadata_extractor.py

Signed-off-by: zhmin <myzhmin@gmail.com>

fix: hive metadata extractor not work on postgresql

---

README.md
databuilder/extractor/delta_lake_metadata_extractor.py
example/scripts/sample_deltalake_metadata.py
setup.py
tests/unit/extractor/test_deltalake_extractor.py

This is the MR for a delta lake amundsen extractor. This approach requires that the extractor runs on a spark cluster and so would need to be executed differently from other types of extractors.
It currently emits both table metadata and table last updated, BUT it can be augmented at a later point to also emit:
- programmatic descriptions with delta-lake specific information
- watermarks
- column stats
Tests for all core extractor functionality were added.
Initial documentation added to the main README.md
- All the public functions and the classes in the …

feat: Adds delta-lake-extractor

---

tests/unit/extractor/test_deltalake_extractor.py
tests/unit/models/test_badge.py

Signed-off-by: Wonyeong Choi <ciwnyg0815@gmail.com>
Since the `assertEquals` function has been deprecated, replaced it with the `assertEqual` function for all test files.
Passed all existing unit tests
pytest doc about deprecated function: https://docs.python.org/3.3/library/unittest.html#deprecated-aliases

chore: Change deprecated pytest function

---

databuilder/models/badge.py
databuilder/models/table_metadata.py
setup.py
tests/unit/models/test_badge.py

Signed-off-by: dikshathakur3119 <dikshathakur@lyft.com>
Adding repr() function to BadgeMetadata so that can be used in unit tests to compare two instances of BadgeMetadata
Removed database and schema from BadgeMetadata since that information is not used anywhere
NA

chore: Add repr function to BadgeMetadata

---

databuilder/extractor/bigquery_usage_extractor.py

Fix for Issue https://github.com/amundsen-io/amundsen/issues/789.
Extracts information about views and tables in the BigQuery Usage Extractor

fix: Allow BigQuery Usage Extractor to extract usage for views

---

.gitignore
setup.py

databuilder version 4.0.2 has missing dependencies, causing `ModuleNotFoundError` when importing  _databuilder/publisher/neo4j_csv_publisher.py_. See [Issue #793](https://github.com/amundsen-io/amundsen/issues/793).
Have added  `Jinja2>=2.10.0,<2.12` and `pandas>=0.21.0,<1.2.0` to _setup.py_, package versions taken from _requirements.txt_.
No test added as only changed _setup.py_ 

fix: Add databuilder missing dependencies

---

databuilder/models/dashboard/dashboard_metadata.py

I noticed that the DashboardMetadata docs are outdated, and reference e.g. 'lastreloadtime' which no longer exists, and is instead implemented in a separate model.
This updates the docs to reflect the current state of Dashboard metadata.

docs: Update DashboardMetadata docs

---

requirements.txt
setup.py

An alternative to #406 : this PR acknowledges that this repo no longer effectively supports any Python versions lower than 3.6, since full typing syntax is used in various modules, and no versions below 3.6 are tested in CI. Therefore, it:
1. Removes the `typing` requirement completely
2. Simplifies `python_requires`
3. Removes the `:python_version=="2.7"` entry from `extras_require`

chore: Remove support for Python<3.6

---

databuilder/publisher/neo4j_csv_publisher.py

Pandas detect missing values as default when reading a csv file. Due this configuration, Pandas was changing empty table and columns' descriptions to 'nan'. The solution is add one parameter when reading these csv files on **pandas.read_csv( )** method
also passing **na_filter=False** can improve the performance of reading a large file.
N/A
The documentation comes from oficial [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) lib
- All the public functions and the classes in the PR contain docstrings that explain …

fix: pandas 'nan' values when loading csv files

---

databuilder/models/column_usage_model.py
databuilder/models/table_column_usage.py

Signed-off-by: Andrew <andrjc4@vt.edu>
When the read counts are read from a csv they are read as a string not an integer. This ensures all read counts are ints. 

fix: Cast the read counts in the table usage models to be ints

---

databuilder/models/table_stats.py
tests/unit/models/test_table_stats.py

Signed-off-by: Andrew <andrjc4@vt.edu>
This change makes it so all stat values are casted with a string. In the past there was some inconsistencies on if this should be a integer value or a string value. This change here makes it so its consistently treated as a string. 
Modified the table stats test so it expects a string. 

fix: Table stat values should always be represented with a string 

---

databuilder/extractor/feast_extractor.py
example/scripts/sample_feast_loader.py
setup.py
tests/unit/extractor/test_feast_extractor.py

This PR provider Extractor for [Feast](https://feast.dev/) feature store, announced in https://github.com/amundsen-io/amundsen/issues/815. Apart from FeatureTables definitions, the extractor also pushes the metadata collected by Feast as programmatic descriptions, so they look like this on the Frontend:
The new "extra" dependency is added: `feast` (python sdk for Feast), it is distributed [on ASF licence](https://github.com/feast-dev/feast/blob/master/LICENSE). 
Fixes amundsen-io/amundsen#815
Unit tests for the extractor class.
A sample job with loader definition, doc strings for FeastExtractor class and `extract` method
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party …

feat: Feast extractor

---

databuilder/extractor/csv_extractor.py
example/sample_data/sample_badges.csv
example/scripts/sample_data_loader.py

Added CsvTableBadgeExtractor to be able to load badges using csv files. Also added badges to sample app.
N/A
N/A

feat: adding CsvTableBadgeExtractor

---

README.md

Fix a small typo in the documentation and remove the word `below` as there was no `where` clause pointing in the documentation.
Modified documentation to fix a typo

docs: Fix typo and space

---

databuilder/extractor/base_bigquery_extractor.py
databuilder/extractor/bigquery_metadata_extractor.py

Fix the issue that some table keys of sharded tables are missing from BQ metadata extractor. Currently, there is a set 'grouped_tables' storing table_prefix of sharded tables to avoid duplicate metadata records, but it is possible the table prefixes would be same in different datasets. 
Related issue: [833](https://github.com/amundsen-io/amundsen/issues/833)
Sharded tables will use the concatenation of dataset_id & table_id as the key of set 'grouped_tables' in bigquery_metadata_extractor
No more tests were added and current test can still work
More details are in [issue 833](https://github.com/amundsen-io/amundsen/issues/833)
- In case you are adding a dependency, check if the license complies with the [ASF 3rd …

fix: Use dataset_id & table_id as the key of set 'grouped_tables' in bigquery_metadata_extractor

---

databuilder/extractor/dashboard/redash/redash_dashboard_extractor.py
databuilder/extractor/dashboard/redash/redash_dashboard_utils.py
tests/unit/extractor/dashboard/redash/test_redash_dashboard_extractor.py
tests/unit/extractor/dashboard/redash/test_redash_dashboard_utils.py

Fix issues in redash dashboard exporter and added a few tests
modified unit test

fix: fix redash dashboard exporter

---

setup.py

As seen here: https://github.com/laughingman7743/PyAthena/issues/189
The 2.0.0 version of PyAthena doesn't install SQLAlchemy for some reason
This PR fixes that
This issue can be reproduced in a similar way to the linked Issue:
```bash
$ mkdir /tmp/test
$ cd /tmp/test
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ echo 'amundsen-databuilder[athena]==4.0.3' > requirements.txt
(venv) $ pip3 install -r requirements.txt 2>/dev/null | grep Ignoring
Ignoring sqlalchemy: markers 'extra == "SQLAlchemy"' don't match your environment
```
This fix just ignores version 2.0.0 for now, presumably until that dependency issue is fixed.
As this is a dependency issue I don't think there's a test that can be run 🤷‍♂️ 
- In case you are adding a dependency, check if the license complies with the …

fix: Address PyAthena dependency problem

---

databuilder/extractor/base_bigquery_extractor.py
databuilder/extractor/bigquery_metadata_extractor.py

Signed-off-by: xuans <xuan_shen@outlook.com>
It is an update for my previous PR(https://github.com/amundsen-io/amundsendatabuilder/pull/421) which uses dataset/table_prefix as the key of grouped_tables to solve the table key missing issue since some tables can share the same table_prefix in different datasets. I just noticed the Set self.grouped_tables is only used for a single function `_retrieve_tables()` in bigquery_metadata_extractor. If so, for fixing that issue, I would like to just move grouped_tables into `_retrieve_tables()` which only works for a given dataset so that this set can still use table_prefix as the key. It is going to make the code change conciser.
- In case you are adding a dependency, check …

fix: Move grouped_tables into _retrieve_tables() in bigquery_metadata_extractor

---

databuilder/extractor/atlas_search_data_extractor.py
example/scripts/sample_atlas_search_extractor.py
requirements.txt
setup.py

This MR introduces extractor to populate Elasticsearch with Atlas data. This way users can use Atlas as metadata proxy while search using ES Proxy.
todo
todo
- [] PR passes `make test`

feat: Atlas Search Extractor

---

databuilder/extractor/sql_alchemy_extractor.py
tests/unit/extractor/test_sql_alchemy_extractor.py

I added a config key for the `SQLAlchemyExtractor` that lets the user specify general `connect_args` for the `sqlalchemy.create_engine` function. I did this because I want to use the `SQLAlchemyExtractor` for Presto and I have an https connection so I need to pass the kwarg `connect_args={"protocol": "https"}` into `create_engine`. 
I added the test: test_get_connection in tests/unit/extractor/test_sql_alchemy_extractor.py
I did not add any documentation

feat: Add config key for connect_arg for SqlAlchemyExtractor

---

databuilder/extractor/hive_table_metadata_extractor.py

Signed-off-by: benrifkind <ben.rifkind@gmail.com>
Changed the logging of the SQL query to format as string instead of integer. I am pretty sure this was a typo. This is to fix this error I get when running a HiveTableMetadataExtractor job.
```
TypeError: %i format: a number is required, not str
```
No tests. This is a typo fix.
None,

fix: Change logging formatting typo

---

databuilder/extractor/dashboard/tableau/tableau_dashboard_extractor.py
databuilder/extractor/dashboard/tableau/tableau_dashboard_last_modified_extractor.py
tests/unit/extractor/dashboard/tableau/test_tableau_dashboard_extractor.py
tests/unit/extractor/dashboard/tableau/test_tableau_dashboard_last_modified_extractor.py

Closes: amundsen-io/amundsen#911
Tableau API returns null for dashboard name or project name when the user token does not have access privilege for the dashboard or the project.
The sanitizers in `TableauDashboardUtils` will raise `TypeError` when the value is None.
If these names are None, we should ignore them and shows some warnings.
No feature added.

fix: Ignore Tableau dashboards of insufficient privileges

---

README.md
databuilder/extractor/dashboard/redash/redash_dashboard_extractor.py
tests/unit/extractor/dashboard/redash/test_redash_dashboard_extractor.py

Redash v8 and v9 have different resource urls for dashboards. The current behaviour is consistent with v9, which is currently in beta.
This adds `redash_version` as an optional config parameter to `RedashDashboardExtractor`, and uses the value of this parameter to determine the urls for dashboards.
A test was added to [tests/unit/extractor/dashboard/redash/test_redash_dashboard_extractor.py](tests/unit/extractor/dashboard/redash/test_redash_dashboard_extractor.py) to test that the correct api url is called when `redash_version` is set to `8`
`redash_version` was added to the README.md
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License …

fix: Use Redash Version to determine API URLs

---

setup.py

This PR fixes an issue wherein this package could not be installed with the `bigquery` extra because a comma was missing between two package specifications. Python allows this as a multi-line string, so both requirements are concatenated and neither can be found.
Resolves amundsen-io/amundsen#938
No tests were modified
No documentation needed to be changed, this was a change to align with expected behavior.

fix: Add comma between bigquery requirements listings

---

databuilder/extractor/athena_metadata_extractor.py
databuilder/extractor/druid_metadata_extractor.py
databuilder/extractor/mssql_metadata_extractor.py
databuilder/extractor/presto_view_metadata_extractor.py
databuilder/extractor/snowflake_metadata_extractor.py
databuilder/extractor/snowflake_table_last_updated_extractor.py
databuilder/extractor/sql_alchemy_extractor.py

This addresses #868, where extractions using the Snowflake extractor would
hand until the connection was closed. I've added close() calls to the other
SQL Alchemy based extractors since it is a general expectation of SQL Alchemy
and most of the infrastructure existed to do it already.
Is there a good way of testing these extractor classes without requiring the appropriate DB to be available?
Test coverage in this project is already significantly below the goal of 70%, so `make test` is failing for me. This happens regardless of these changes.
Closing connections is an expected behavior, so I did not add specific documentation.
- In case you are adding a dependency, check if the license complies with the [ASF 3rd …

fix: Close SQL Alchemy connections.

---

databuilder/extractor/athena_metadata_extractor.py
databuilder/extractor/druid_metadata_extractor.py
databuilder/extractor/mssql_metadata_extractor.py
databuilder/extractor/presto_view_metadata_extractor.py
databuilder/extractor/snowflake_metadata_extractor.py
databuilder/extractor/snowflake_table_last_updated_extractor.py
databuilder/extractor/sql_alchemy_extractor.py

Without checking the existence of the `_alchemy_extractor` attribute, and that
the value is not None, an AttributeError can be raised when close() is called
if the init method didn't complete. Tasks still call close to clean up, so
this code should check if there is anything to clean up first.
No tests were added. I am not familiar enough with mocking to set up effective tests.
No documentation was added.

fix: Avoid error by checking for existence before close.

---

databuilder/extractor/dashboard/tableau/tableau_dashboard_extractor.py
databuilder/extractor/dashboard/tableau/tableau_dashboard_last_modified_extractor.py
databuilder/extractor/dashboard/tableau/tableau_dashboard_query_extractor.py
databuilder/extractor/dashboard/tableau/tableau_dashboard_table_extractor.py

If I don't give any value to job config's `EXCLUDED_PROJECTS` key, `get_list` method of config_tree gives a following exception.
> pyhocon.exceptions.ConfigMissingException: 'No configuration setting found for key excluded_projects'
Therefore, we can cope with this situation by giving a default value.
I don't think there is a need for testing because the situation that I'm trying to prevent is not what you normally want. Nevertheless, when giving an empty list to config, I think it's good to make it work well even if you don't give any value.
N/A
- All …

fix: Add default empty list when parse tableau_excluded_projects from config

---

databuilder/models/table_metadata.py
setup.py
tests/unit/models/test_description_metadata.py

Make DescriptionMetadata inherit from GraphSerializable. The change is backward compatible. DescriptionMetadata can still be created along with TableMetadata, ColumnMetadata, or SchemaModel. At the same time, DescriptionMetadata can now created independently, as long as node key, relation start key, relation start label are provided. 
1. Add tests for descriptionmetadata to ensure Exception is raised if required data is missing when creating a node or a relation
2. Add tests for Graph serialization.
- All the public functions and the classes in the PR …

feat: Make DescriptionMetadata inherit from GraphSerializable

---

setup.py

Signed-off-by: hhobson <hugo.hobson@dazn.com>
`databuilder` version 4.2.1 is missing `amundsen-rds` package. Have added package and with no version pinning as presume will always want to use latest.
No test added as only changed setup.py

fix: Add missing amundsen-rds package

---

databuilder/extractor/dashboard/tableau/tableau_dashboard_extractor.py
databuilder/extractor/dashboard/tableau/tableau_dashboard_utils.py
tests/unit/extractor/dashboard/tableau/test_tableau_dashboard_extractor.py

Tableau supports multi-tenancy as a "site", but the current databuilder implementation does not support the feature.
Now, dashboard_url and dashboard_group_url contain site name (e.g. https://tableau-server/#/site/my-site/...).
Add some test cases to check dashboard_url and dashboard_group_url

fix: add support for Tableau multi-site deployment

---

databuilder/extractor/mysql_search_data_extractor.py
databuilder/loader/file_system_mysql_csv_loader.py
databuilder/publisher/mysql_csv_publisher.py
example/scripts/sample_data_loader_mysql.py
requirements.txt
setup.py
tests/unit/extractor/test_mysql_search_data_extractor.py
tests/unit/loader/test_file_system_mysql_csv_loader.py
tests/unit/models/test_table_serializable.py
tests/unit/publisher/test_mysql_csv_publisher.py
tests/unit/resources/fs_mysql_csv_loader/records/actor_0.csv
tests/unit/resources/fs_mysql_csv_loader/records/movie_0.csv
tests/unit/resources/fs_mysql_csv_loader/records/movie_actor_1.csv
tests/unit/resources/mysql_csv_publisher/records/actor_0.csv
tests/unit/resources/mysql_csv_publisher/records/movie_0.csv
tests/unit/resources/mysql_csv_publisher/records/movie_actor_1.csv

A feature supporting [RFC:support-mysql-as-backend-store](https://github.com/amundsen-io/rfcs/blob/master/rfcs/023-support-mysql-as-backend-store.md)
Main changes:
- fs\_mysql\_csv\_loader
Read data from record_iterator and the output are csv files, {tablename}\_{key}.csv
- mysql\_csv\_publisher
Read csv files and publish records to mysql with rds orm models.
- mysql\_search\_extractor
Retrieve metadata stored in mysql and outputs instances of the given model or raw results.
- sample_data_loader_mysql
Sample script for publishing metadata into mysql. The script can not work until db init(in dev) is finished and for now, is mainly used to show how ETL works for mysql in the databuilder. (This note was also marked as TODO in the script)
- Pinned sqlalchemy >=1.3.6, < 1.4 to support …

feat: Add mysql as backend store

---

databuilder/task/mysql_staleness_removal_task.py
tests/unit/task/test_mysql_staleness_removal_task.py

Signed-off-by: Sahithi Velma <sahithiv@wepay.com>
Adds a stale data removal task for mysql metadata store
Added unit tests for the mysql_staleness_removal_task
N/A

feat: Add mysql staleness removal task
